import { useMemo } from 'react';
import { Dimensions, Platform, StyleSheet } from 'react-native';
import { useTheme } from '@/theme/ThemeProvider';
import type { ThemeColors } from '@/theme/types';
import { normalize } from '@/utils/normalize';

const { width } = Dimensions.get('window');
const GRID_ITEM_SIZE = (width - 48) / 2;

export function createFileManagementStyles(colors: ThemeColors) {
  return StyleSheet.create({
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 10,
      paddingVertical: 12,
      backgroundColor: colors.background,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    iconBtn: {
      width: 32,
      height: 32,
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      fontSize: 18,
      color: colors.textPrimary,
    },
    contentArea: {
      flex: 1,
      padding: 16,
      paddingTop: 0,
      paddingBottom: 24,
    },
    topChrome: {
      backgroundColor: colors.background,
    },
    modeBar: {
      height: 52,
      justifyContent: 'center',
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    modeScrollContent: {
      paddingHorizontal: Platform.OS === 'ios' ? 5 : 12,
      alignItems: 'center',
    },
    modeChip: {
      height: 36,
      justifyContent: 'center',
      paddingHorizontal: 14,
      borderRadius: 20,
      backgroundColor: colors.categoryChip,
      marginRight: 8,
    },
    modeChipActive: {
      backgroundColor: colors.surfaceElevated,
    },
    modeChipText: {
      color: colors.messageMeta,
    },
    modeChipTextActive: {
      color: colors.primary,
    },
    searchWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 5,
      marginTop: 10,
      marginBottom: 8,
      backgroundColor: colors.surfaceElevated,
      borderRadius: 12,
      paddingHorizontal: 12,
      height: 42,
      borderWidth: 1,
      borderColor: colors.border,
    },
    searchInput: {
      flex: 1,
      marginLeft: 8,
      color: colors.textPrimary,
      fontSize: 15,
      paddingVertical: 0,
    },
    filtersBar: {
      height: 44,
      justifyContent: 'center',
      marginBottom: 2,
    },
    filtersContent: {
      paddingHorizontal: Platform.OS === 'ios' ? 5 : 12,
      alignItems: 'center',
    },
    filterChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 10,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      marginRight: 8,
    },
    filterChipActive: {
      backgroundColor: colors.surfaceElevated,
      borderColor: colors.primary,
    },
    filterChipText: {
      color: colors.textPrimary,
    },
    filterChipTextActive: {
      color: colors.primary,
    },
    toolbar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: Platform.OS === 'ios' ? 5 : 12,
      paddingTop: 8,
      paddingBottom: 4,
      backgroundColor: colors.background,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    tabs: {
      flexDirection: 'row',
      gap: 18,
      marginBottom: 20,
    },
    tabBtn: {
      paddingBottom: 10,
      position: 'relative',
    },
    tabText: {
      color: colors.messageMeta,
      fontSize: 15,
    },
    tabTextActive: {
      color: colors.primary,
    },
    tabUnderline: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      height: 3,
      borderRadius: 2,
      backgroundColor: colors.primary,
    },
    sortBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 2,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
      backgroundColor: colors.surfaceElevated,
    },
    sortText: {
      color: colors.textPrimary,
    },
    gridContent: {},
    gridRow: {
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    gridItem: {
      width: GRID_ITEM_SIZE,
      backgroundColor: colors.surface,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: 'hidden',
      paddingBottom: 10,
    },
    gridItemSelected: {
      borderColor: colors.primary,
      backgroundColor: colors.surfaceElevated,
    },
    selectionBadge: {
      position: 'absolute',
      top: 10,
      right: 10,
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 2,
      borderColor: colors.primary,
      backgroundColor: colors.surface,
      zIndex: 2,
      alignItems: 'center',
      justifyContent: 'center',
    },
    selectionBadgeActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    selectionBar: {
      position: 'absolute',
      left: 16,
      right: 16,
      bottom: 24,
      backgroundColor: colors.textPrimary,
      borderRadius: 14,
      paddingHorizontal: 16,
      paddingVertical: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      zIndex: 60,
      elevation: 8,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
    },
    selectionCount: {
      color: colors.background,
    },
    selectionActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    selectionDeleteBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.error,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 10,
    },
    selectionDeleteText: {
      color: colors.white,
    },
    selectionMoveBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.primary,
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 10,
    },
    selectionMoveBtnDisabled: {
      opacity: 0.45,
    },
    selectionMoveText: {
      color: colors.white,
    },
    cancelSelectText: {
      color: colors.primary,
      fontSize: 13,
    },
    gridImage: {
      width: '100%',
      height: GRID_ITEM_SIZE - 20,
      backgroundColor: colors.surfaceElevated,
    },
    gridVideoThumb: {
      backgroundColor: colors.black,
      overflow: 'hidden',
      position: 'relative',
    },
    gridVideoImage: {
      ...StyleSheet.absoluteFillObject,
      opacity: 0.7,
    },
    gridVideoOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0,0,0,0.4)',
    },
    gridPlaceholder: {
      width: '100%',
      height: GRID_ITEM_SIZE - 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    folderPlaceholder: {
      backgroundColor: colors.surfaceElevated,
    },
    gridPlay: {
      position: 'absolute',
      top: (GRID_ITEM_SIZE - 20) / 2 - 22,
      alignSelf: 'center',
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: 'rgba(0,0,0,0.55)',
      borderWidth: 2,
      borderColor: 'rgba(255,255,255,0.9)',
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 2,
      paddingLeft: 3,
    },
    gridName: {
      color: colors.textPrimary,
      paddingHorizontal: 10,
      paddingTop: 8,
    },
    gridSize: {
      color: colors.messageMeta,
      paddingHorizontal: 10,
      paddingTop: 2,
    },
    listEmptyContent: {
      flexGrow: 1,
    },
    emptyState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 32,
      paddingVertical: 24,
    },
    emptyStateInline: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 32,
      paddingVertical: 48,
    },
    emptyTitle: {
      color: colors.textPrimary,
      fontSize: 17,
      marginTop: 12,
      fontWeight: '600',
    },
    emptySubtitle: {
      color: colors.messageMeta,
      fontSize: 14,
      marginTop: 6,
      textAlign: 'center',
    },
    loadingWrap: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 48,
    },
    retryBtn: {
      marginTop: 16,
      backgroundColor: colors.primary,
      borderRadius: 10,
      paddingHorizontal: 18,
      paddingVertical: 10,
    },
    retryText: {
      color: colors.white,
    },
    footerLoader: {
      paddingVertical: 16,
      alignItems: 'center',
    },
    sheetBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.35)',
      justifyContent: 'flex-end',
    },
    sheetContainer: {
      backgroundColor: colors.surface,
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
      maxHeight: '72%',
      paddingBottom: 24,
    },
    sheetHandle: {
      width: 42,
      height: 4,
      borderRadius: 2,
      backgroundColor: colors.border,
      alignSelf: 'center',
      marginTop: 10,
      marginBottom: 12,
    },
    sheetTitle: {
      paddingHorizontal: 20,
      marginBottom: 12,
      color: colors.textPrimary,
    },
    sheetSearchWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 16,
      marginBottom: 8,
      backgroundColor: colors.surfaceElevated,
      borderRadius: 10,
      paddingHorizontal: 12,
      height: 40,
      borderWidth: 1,
      borderColor: colors.border,
    },
    sheetSearchInput: {
      flex: 1,
      marginLeft: 8,
      color: colors.textPrimary,
      fontSize: 15,
      paddingVertical: 0,
    },
    sheetList: {
      paddingHorizontal: 8,
    },
    sheetItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 14,
      gap: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    sheetItemText: {
      flex: 1,
      color: colors.textPrimary,
    },
    sheetApplyBtn: {
      marginTop: 8,
      marginHorizontal: 16,
      marginBottom: 12,
      backgroundColor: colors.primary,
      borderRadius: 10,
      paddingVertical: 12,
      alignItems: 'center',
    },
    sheetApplyText: {
      color: colors.white,
    },
    sheetAvatar: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sheetSubtitle: {
      paddingHorizontal: 20,
      color: colors.messageMeta,
      marginTop: 4,
      marginBottom: 8,
    },
    destructiveText: {
      color: colors.error,
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.45)',
      justifyContent: 'center',
      paddingHorizontal: 24,
    },
    modalCard: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 20,
      maxHeight: '80%',
    },
    modalTitle: { color: colors.textPrimary },
    modalSubtitle: {
      color: colors.messageMeta,
      marginTop: 6,
      marginBottom: 16,
    },
    modalInput: {
      height: 46,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
      paddingHorizontal: 14,
      color: colors.textPrimary,
      fontSize: 15,
      backgroundColor: colors.surfaceElevated,
    },
    modalActions: {
      flexDirection: 'row',
      gap: 12,
      marginTop: 20,
    },
    modalCancelBtn: {
      flex: 1,
      height: 46,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalCancelText: { color: colors.textMuted },
    modalPrimaryBtn: {
      flex: 1,
      height: 46,
      borderRadius: 10,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalPrimaryBtnDisabled: { opacity: 0.6 },
    modalPrimaryText: { color: colors.white },
    modalFileRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
      gap: 12,
    },
    modalFileIcon: {
      width: 40,
      height: 40,
      borderRadius: 10,
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
    },
    modalFileInfo: { flex: 1, minWidth: 0 },
    modalFileName: { color: colors.textPrimary },
    modalFileSize: { color: colors.messageMeta, marginTop: 2 },
    modalRemoveBtn: { padding: 4 },
    modalList: { maxHeight: 280 },
    moveSheetSubtitle: {
      paddingHorizontal: 20,
      color: colors.messageMeta,
      marginTop: 4,
      marginBottom: 12,
    },
    moveSheetLoader: {
      paddingVertical: 40,
      alignItems: 'center',
    },
    moveSheetEmpty: {
      paddingVertical: 32,
      alignItems: 'center',
    },
    moveSheetEmptyText: { color: colors.messageMeta },
    moveFolderIcon: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
    },
    moveFolderInfo: { flex: 1 },
    moveFolderName: { color: colors.textPrimary },
    moveFolderCount: { color: colors.messageMeta, marginTop: 2 },
    popoverWrapper: { ...StyleSheet.absoluteFillObject, zIndex: 50 },
    popoverOverlay: { ...StyleSheet.absoluteFillObject },
    popoverFab: {
      position: 'absolute',
      right: normalize(20),
      bottom: normalize(20),
      width: normalize(56),
      height: normalize(56),
      borderRadius: normalize(28),
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 5,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      zIndex: 100,
    },
    popoverFabActive: { backgroundColor: colors.secondary },
    popoverPlusIcon: { width: 24, height: 24, tintColor: colors.white },
    popoverCard: {
      position: 'absolute',
      right: normalize(20),
      bottom: normalize(80),
      backgroundColor: colors.surface,
      borderRadius: normalize(12),
      width: normalize(210),
      paddingVertical: normalize(4),
      zIndex: 101,
      ...Platform.select({
        ios: {
          shadowColor: colors.black,
          shadowOffset: { width: 0, height: 12 },
          shadowOpacity: 0.15,
          shadowRadius: 16,
        },
        android: { elevation: 12 },
      }),
    },
    popoverMenuItem: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: normalize(16),
    },
    popoverMenuIcon: { marginRight: 12 },
    popoverMenuText: { color: colors.textPrimary },
    popoverSeparator: {
      height: 1,
      backgroundColor: colors.categoryChip,
      marginHorizontal: normalize(16),
    },
    listRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
      backgroundColor: colors.surface,
    },
    listRowSelected: {
      backgroundColor: colors.surfaceElevated,
    },
    listNameCell: {
      flex: 2.2,
      flexDirection: 'row',
      alignItems: 'center',
      minWidth: 0,
      paddingRight: 8,
    },
    listIconWrap: {
      width: 34,
      height: 34,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
      overflow: 'hidden',
    },
    listThumbnail: {
      width: '100%',
      height: '100%',
    },
    listPlayBadge: {
      position: 'absolute',
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: 'rgba(0,0,0,0.55)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    listFileName: {
      flex: 1,
      color: colors.textPrimary,
    },
    listOwnerCell: {
      flex: 1.4,
      flexDirection: 'row',
      alignItems: 'center',
      minWidth: 0,
      paddingRight: 6,
    },
    listAvatar: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 6,
    },
    listAvatarText: {
      color: colors.primary,
    },
    listOwnerName: {
      flex: 1,
      color: colors.textMuted,
    },
    listAccessCell: {
      width: 58,
      alignItems: 'flex-start',
    },
    listAccessText: {
      color: colors.messageMeta,
    },
    listSizeText: {
      width: 72,
      color: colors.messageMeta,
      textAlign: 'right',
    },
    previewCard: {
      backgroundColor: colors.black,
      borderRadius: 16,
      overflow: 'hidden',
      minHeight: 240,
      justifyContent: 'center',
    },
    imagePreview: {
      width: '100%',
      height: 280,
      backgroundColor: colors.black,
    },
    videoPreview: {
      width: '100%',
      height: 280,
      backgroundColor: colors.black,
    },
    videoTouchOverlay: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: 'center',
      alignItems: 'center',
    },
    playCircle: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      paddingLeft: 4,
    },
    videoControls: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 14,
      paddingVertical: 12,
      backgroundColor: colors.black,
    },
    slider: {
      flex: 1,
      height: 28,
      marginHorizontal: 8,
    },
    timeLabel: {
      color: colors.white,
      width: 42,
      textAlign: 'center',
    },
    audioCard: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 20,
      alignItems: 'center',
    },
    audioTitle: {
      color: colors.textPrimary,
      textAlign: 'center',
      marginTop: 14,
    },
    audioMeta: {
      color: colors.messageMeta,
      marginTop: 6,
      marginBottom: 16,
    },
    audioPlayerWrap: {
      width: '100%',
    },
    docCard: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 24,
      alignItems: 'center',
    },
    docIcon: {
      width: 72,
      height: 72,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    docLabel: {
      color: colors.white,
      fontSize: 18,
    },
    docTitle: {
      color: colors.textPrimary,
      textAlign: 'center',
      marginTop: 16,
      maxWidth: width - 80,
    },
    docMeta: {
      color: colors.messageMeta,
      marginTop: 6,
    },
    openDocBtn: {
      marginTop: 20,
      backgroundColor: colors.primary,
      borderRadius: 12,
      paddingHorizontal: 18,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      minWidth: 180,
      justifyContent: 'center',
    },
    openDocText: {
      color: colors.white,
    },
    detailHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 10,
      paddingVertical: 12,
      backgroundColor: colors.background,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    detailIconBtn: {
      width: 36,
      height: 36,
      justifyContent: 'center',
      alignItems: 'center',
    },
    detailHeaderTitle: {
      flex: 1,
      textAlign: 'center',
      fontSize: 18,
      color: colors.textPrimary,
      paddingHorizontal: 8,
    },
    detailHeaderActions: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    detailCentered: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 24,
    },
    detailErrorText: {
      color: colors.messageMeta,
      textAlign: 'center',
    },
    detailContent: {
      padding: 16,
      paddingBottom: 32,
      gap: 16,
    },
    detailInfoCard: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 18,
    },
    detailFileName: {
      color: colors.textPrimary,
      marginBottom: 16,
    },
    detailOwnerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    detailAvatar: {
      width: 42,
      height: 42,
      borderRadius: 21,
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
    },
    detailAvatarText: {
      color: colors.primary,
    },
    detailMetaLabel: {
      color: colors.messageMeta,
      marginBottom: 2,
    },
    detailDivider: {
      height: 1,
      backgroundColor: colors.border,
      marginVertical: 16,
    },
    detailRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      paddingVertical: 10,
      gap: 16,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    detailLabel: {
      color: colors.messageMeta,
      width: 110,
    },
    detailValue: {
      flex: 1,
      color: colors.textPrimary,
      textAlign: 'right',
    },
  });
}

export function useFileManagementStyles() {
  const { colors } = useTheme();
  return useMemo(() => createFileManagementStyles(colors), [colors]);
}

/** @deprecated Use `useFileManagementStyles()` for theme-aware styles. */
export const fileManagementStyles = createFileManagementStyles({
  primary: '#6C47FF',
  primaryforeground: '#7141F8',
  secondary: '#303073',
  secondaryforeground: '#D3C4FD33',
  white: '#FFFFFF',
  black: '#000000',
  transparent: 'transparent',
  background: '#FFFFFF',
  surface: '#FFFFFF',
  surfaceElevated: '#F8F9FA',
  textPrimary: '#000000',
  textSecondary: '#666666',
  textMuted: '#333333',
  textMain: '#000000',
  border: '#E5E5E5',
  error: '#FF3B30',
  online: '#22C55E',
  offline: '#9095A1',
  bgSecondary: '#F8F9FA',
  topNavigation: '#F2F2FF',
  lightBlue: '#f7f7fc',
  lightYellow: '#f3ffc1',
  tabBar: '#FFFFFF',
  tabBarBorder: '#E5E5E5',
  iconDefault: '#54656F',
  iconMuted: '#C4C4C6',
  chatSentBubble: '#F2F2FF',
  chatReceivedBubble: '#FFFFFF',
  chatHighlight: '#f3ffc1',
  channelMentionBackground: '#FFE066',
  channelMentionForeground: '#CA8A04',
  categoryChip: '#F3F4F6',
  skeleton: '#E1E9EE',
  messageMeta: '#667781',
  reactionBackground: '#F0F2F5',
  threadBarBackground: '#F7F7F8',
  dateHeaderBackground: 'rgba(255, 255, 255, 0.8)',
  channelAvatarBackground: 'rgba(0, 52, 115, 0.18)',
  waveformInactive: '#C8CCCE',
  statusBarStyle: 'dark-content',
  statusBarBackground: '#FFFFFF',
});
