import { Dimensions, Platform, StyleSheet } from 'react-native';
import { Colors } from '@/theme/colors';

const { width } = Dimensions.get('window');
const GRID_ITEM_SIZE = (width - 48) / 2;

export const fileManagementStyles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 12,
    backgroundColor: '#FFF',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#E9EDEF',
  },
  iconBtn: { width: 32, height: 32, justifyContent: 'center', alignItems: 'center' },
  headerTitle: { flex: 1, textAlign: 'center', fontSize: 18, color: '#222' },
  contentArea: {
    flex: 1,
    padding: 16,
    paddingTop: 0,
    paddingBottom: 24,
  },
  topChrome: {
    backgroundColor: '#FFF',
  },
  modeBar: {
    height: 52,
    justifyContent: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#ECECEC',
  },
  modeScrollContent: {
    paddingHorizontal: Platform.OS === 'ios' ? 5 : 12,
    alignItems: 'center',
  },
  modeChip: {
    height: 36,
    justifyContent: 'center',
    paddingHorizontal: 14,
    borderRadius: 20,
    backgroundColor: '#F4F4F6',
    marginRight: 8,
  },
  modeChipActive: {
    backgroundColor: '#F4EDFF',
  },
  modeChipText: {
    color: '#667781',
  },
  modeChipTextActive: {
    color: Colors.primary,
  },
  searchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 5,
    marginTop: 10,
    marginBottom: 8,
    backgroundColor: '#F8F9FA',
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 42,
    borderWidth: 1,
    borderColor: '#ECECEC',
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    color: '#1D1C1D',
    fontSize: 15,
    paddingVertical: 0,
  },
  filtersBar: {
    height: 44,
    justifyContent: 'center',
    marginBottom: 2,
  },
  filtersContent: {
    paddingHorizontal: Platform.OS === 'ios' ? 5 : 12,
    alignItems: 'center',
  },
  filterChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#E5E5E5',
    marginRight: 8,
  },
  filterChipActive: {
    backgroundColor: '#F4EDFF',
    borderColor: '#D8CCFF',
  },
  filterChipText: {
    color: '#3B3B3B',
  },
  filterChipTextActive: {
    color: Colors.primary,
  },
  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: Platform.OS === 'ios' ? 5 : 12,
    paddingTop: 8,
    paddingBottom: 4,
    backgroundColor: '#FFF',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#ECECEC',
  },
  tabs: {
    flexDirection: 'row',
    gap: 18,
    marginBottom: 20,
  },
  tabBtn: {
    paddingBottom: 10,
    position: 'relative',
  },
  tabText: {
    color: '#667781',
    fontSize: 15,
  },
  tabTextActive: {
    color: Colors.primary,
  },
  tabUnderline: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 3,
    borderRadius: 2,
    backgroundColor: Colors.primary,
  },
  sortBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#F8F9FA',
  },
  sortText: {
    color: '#3B3B3B',
  },
  gridContent: {},
  gridRow: {
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  gridItem: {
    width: GRID_ITEM_SIZE,
    backgroundColor: '#FFF',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#ECECEC',
    overflow: 'hidden',
    paddingBottom: 10,
  },
  gridItemSelected: {
    borderColor: Colors.primary,
    backgroundColor: '#FBF8FF',
  },
  selectionBadge: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: Colors.primary,
    backgroundColor: '#FFF',
    zIndex: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectionBadgeActive: {
    backgroundColor: Colors.primary,
    borderColor: Colors.primary,
  },
  selectionBar: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 24,
    backgroundColor: '#1D1C1D',
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    zIndex: 60,
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  selectionCount: {
    color: '#FFF',
  },
  selectionActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  selectionDeleteBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#D32F2F',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
  },
  selectionDeleteText: {
    color: '#FFF',
  },
  selectionMoveBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: Colors.primary,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 10,
  },
  selectionMoveBtnDisabled: {
    opacity: 0.45,
  },
  selectionMoveText: {
    color: '#FFF',
  },
  cancelSelectText: {
    color: Colors.primary,
    fontSize: 13,
  },
  gridImage: {
    width: '100%',
    height: GRID_ITEM_SIZE - 20,
    backgroundColor: '#F2F2F2',
  },
  gridVideoThumb: {
    backgroundColor: '#1A1A1A',
    overflow: 'hidden',
    position: 'relative',
  },
  gridVideoImage: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.7,
  },
  gridVideoOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.4)',
  },
  gridPlaceholder: {
    width: '100%',
    height: GRID_ITEM_SIZE - 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  folderPlaceholder: {
    backgroundColor: '#F4EDFF',
  },
  gridPlay: {
    position: 'absolute',
    top: (GRID_ITEM_SIZE - 20) / 2 - 22,
    alignSelf: 'center',
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0,0,0,0.55)',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
    paddingLeft: 3,
  },
  gridName: {
    color: '#1D1C1D',
    paddingHorizontal: 10,
    paddingTop: 8,
  },
  gridSize: {
    color: '#8696A0',
    paddingHorizontal: 10,
    paddingTop: 2,
  },
  listEmptyContent: {
    flexGrow: 1,
  },
  emptyState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
    paddingVertical: 24,
  },
  emptyStateInline: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 32,
    paddingVertical: 48,
  },
  emptyTitle: {
    color: '#1D1C1D',
    fontSize: 17,
    marginTop: 12,
    fontWeight: '600',
  },
  emptySubtitle: {
    color: '#8696A0',
    fontSize: 14,
    marginTop: 6,
    textAlign: 'center',
  },
  loadingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 48,
  },
  retryBtn: {
    marginTop: 16,
    backgroundColor: Colors.primary,
    borderRadius: 10,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  retryText: {
    color: '#FFF',
  },
  footerLoader: {
    paddingVertical: 16,
    alignItems: 'center',
  },
  sheetBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'flex-end',
  },
  sheetContainer: {
    backgroundColor: '#FFF',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    maxHeight: '72%',
    paddingBottom: 24,
  },
  sheetHandle: {
    width: 42,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#D9D9D9',
    alignSelf: 'center',
    marginTop: 10,
    marginBottom: 12,
  },
  sheetTitle: {
    paddingHorizontal: 20,
    marginBottom: 12,
    color: '#1D1C1D',
  },
  sheetSearchWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 16,
    marginBottom: 8,
    backgroundColor: '#F8F9FA',
    borderRadius: 10,
    paddingHorizontal: 12,
    height: 40,
    borderWidth: 1,
    borderColor: '#ECECEC',
  },
  sheetSearchInput: {
    flex: 1,
    marginLeft: 8,
    color: '#1D1C1D',
    fontSize: 15,
    paddingVertical: 0,
  },
  sheetList: {
    paddingHorizontal: 8,
  },
  sheetItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 14,
    gap: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#F0F0F0',
  },
  sheetItemText: {
    flex: 1,
    color: '#1D1C1D',
  },
  sheetApplyBtn: {
    marginTop: 8,
    marginHorizontal: 16,
    marginBottom: 12,
    backgroundColor: Colors.primary,
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
  },
  sheetApplyText: {
    color: '#FFF',
  },
  sheetAvatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#E8E8E8',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
