import { Dimensions, Platform, StyleSheet } from 'react-native';
import { normalize } from '@/utils/normalize';
import type { ThemeColors } from './types';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

export function createBuzzHomeStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.surfaceElevated },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: normalize(16),
      height: normalize(65),
      backgroundColor: colors.secondary,
    },
    headerTitle: {
      fontSize: normalize(18),
      color: colors.white,
    },
    avatarContainer: {
      position: 'relative',
    },
    avatarImage: {
      width: normalize(36),
      height: normalize(36),
      borderRadius: normalize(18),
      borderWidth: 1,
      borderColor: colors.border,
    },
    activeIndicator: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: normalize(11),
      height: normalize(11),
      borderRadius: normalize(6),
      backgroundColor: colors.online,
      borderWidth: 2,
      borderColor: colors.white,
    },
    actionSection: {
      paddingHorizontal: normalize(20),
      marginTop: normalize(30),
      marginBottom: normalize(20),
    },
    buttonsRow: {
      flexDirection: 'row',
      gap: normalize(12),
    },
    primaryActionBtn: {
      flex: 1,
      backgroundColor: colors.primary,
      height: normalize(48),
      borderRadius: normalize(8),
      justifyContent: 'center',
      alignItems: 'center',
    },
    primaryActionText: {
      color: colors.white,
      fontSize: normalize(15),
    },
    secondaryActionBtn: {
      flex: 1,
      backgroundColor: colors.surface,
      height: normalize(49),
      borderRadius: normalize(8),
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
    },
    secondaryActionText: {
      color: colors.textSecondary,
      fontSize: normalize(15),
    },
    contentArea: {
      flex: 1,
    },
    carouselItemContainer: {
      alignItems: 'center',
      width: screenWidth,
    },
    illustrationWrapper: {
      width: normalize(250),
      height: normalize(250),
      borderRadius: normalize(125),
      backgroundColor: colors.lightBlue,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: normalize(20),
    },
    illustrationImage: {
      width: '80%',
      height: '80%',
    },
    textContainer: {
      paddingHorizontal: normalize(44),
      alignItems: 'center',
    },
    itemTitle: {
      fontSize: normalize(24),
      color: colors.textPrimary,
      textAlign: 'center',
      marginBottom: normalize(12),
    },
    itemSubtitle: {
      fontSize: normalize(15),
      color: colors.textSecondary,
      textAlign: 'center',
      lineHeight: normalize(22),
    },
    popoverCard: {
      backgroundColor: colors.surface,
      borderRadius: normalize(16),
      width: '100%',
      alignSelf: 'center',
      overflow: 'hidden',
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.2,
      shadowRadius: 15,
      elevation: 10,
    },
    popoverOption: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: normalize(24),
      paddingVertical: normalize(20),
    },
    popoverOptionTitle: {
      fontSize: normalize(18),
      color: colors.textPrimary,
      flex: 1,
    },
    popoverIcon: {
      width: normalize(24),
      height: normalize(24),
      tintColor: colors.textSecondary,
    },
    divider: {
      height: 1,
      backgroundColor: colors.border,
    },
  });
}

/** Shared list/search/filter styles for all-buzzes and live-buzzes-list. */
export function createBuzzListStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.surfaceElevated,
    },
    sectionContainer: {
      paddingHorizontal: normalize(20),
      marginTop: normalize(16),
      marginBottom: normalize(8),
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: normalize(5),
      paddingBottom: normalize(12),
      backgroundColor: colors.secondary,
    },
    backBtn: {
      width: normalize(40),
      height: normalize(40),
      alignItems: 'center',
      justifyContent: 'center',
    },
    headerTitle: {
      fontSize: normalize(18),
      color: colors.white,
    },
    filtersSection: {
      paddingTop: normalize(16),
      paddingBottom: normalize(8),
    },
    searchBar: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      height: normalize(42),
      borderRadius: normalize(10),
      paddingHorizontal: normalize(12),
      marginHorizontal: normalize(20),
      marginBottom: normalize(12),
      borderWidth: 1,
      borderColor: colors.border,
    },
    searchIcon: {
      width: 18,
      height: 18,
      tintColor: colors.textMuted,
      marginRight: 8,
    },
    searchInput: {
      flex: 1,
      fontSize: normalize(15),
      color: colors.textPrimary,
    },
    filterScroll: {
      paddingHorizontal: normalize(20),
      gap: normalize(8),
    },
    filterChip: {
      paddingHorizontal: normalize(16),
      height: normalize(34),
      borderRadius: normalize(20),
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      justifyContent: 'center',
      marginRight: normalize(8),
    },
    filterChipActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    filterChipText: {
      color: colors.textMuted,
    },
    filterChipTextActive: {
      color: colors.white,
    },
    listContent: {
      paddingBottom: normalize(40),
    },
    listContentEmpty: {
      flexGrow: 1,
    },
    emptyWrap: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: normalize(48),
      gap: normalize(8),
    },
    emptyText: {
      color: colors.textMuted,
      textAlign: 'center',
      paddingHorizontal: normalize(24),
    },
    footerLoader: {
      marginVertical: normalize(16),
    },
    sectionTitle: {
      fontSize: normalize(16),
      color: colors.textPrimary,
      marginBottom: normalize(12),
    },
    stateWrap: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: normalize(20),
      gap: normalize(8),
      backgroundColor: colors.surface,
      borderRadius: normalize(12),
      borderWidth: 1,
      borderColor: colors.border,
    },
    buzzRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: normalize(12),
      borderWidth: 1,
      borderColor: colors.border,
      padding: normalize(12),
      marginBottom: normalize(10),
      marginHorizontal: normalize(20),
    },
    buzzIconWrap: {
      position: 'relative',
      width: normalize(40),
      height: normalize(40),
      borderRadius: normalize(20),
      backgroundColor: 'rgba(34, 197, 94, 0.12)',
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: normalize(12),
    },
    buzzIconWrapEnded: {
      backgroundColor: colors.categoryChip,
    },
    titleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: normalize(8),
    },
    titleText: {
      flexShrink: 1,
    },
    statusBadge: {
      paddingHorizontal: normalize(8),
      paddingVertical: normalize(2),
      borderRadius: normalize(10),
    },
    liveDot: {
      position: 'absolute',
      top: 2,
      right: 2,
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.online,
      borderWidth: 1.5,
      borderColor: colors.white,
    },
    buzzInfo: {
      flex: 1,
      marginRight: normalize(10),
    },
    buzzMeta: {
      color: colors.textMuted,
      marginTop: 2,
    },
    joinBtn: {
      minWidth: normalize(64),
      height: normalize(34),
      borderRadius: normalize(8),
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: normalize(12),
    },
    joinText: {
      color: colors.white,
    },
    endedPill: {
      minWidth: normalize(64),
      height: normalize(34),
      borderRadius: normalize(8),
      backgroundColor: colors.categoryChip,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: normalize(12),
    },
    endedText: {
      color: colors.textMuted,
    },
  });
}

export function createBuzzModalStyles(colors: ThemeColors) {
  return StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      padding: normalize(20),
    },
    modalCard: {
      backgroundColor: colors.surface,
      borderRadius: normalize(24),
      paddingHorizontal: normalize(24),
      paddingVertical: normalize(32),
      width: '100%',
      maxWidth: normalize(360),
      alignItems: 'center',
    },
    closeButton: {
      alignSelf: 'flex-end',
      marginBottom: normalize(8),
      padding: normalize(4),
    },
    closeIcon: {
      width: normalize(20),
      height: normalize(20),
      tintColor: colors.textSecondary,
    },
    title: {
      fontSize: normalize(20),
      color: colors.textPrimary,
      textAlign: 'center',
      marginBottom: normalize(16),
    },
    description: {
      fontSize: normalize(15),
      color: colors.textSecondary,
      textAlign: 'center',
      lineHeight: normalize(22),
      marginBottom: normalize(24),
    },
    linkContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surfaceElevated,
      borderRadius: normalize(12),
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: normalize(16),
      height: normalize(56),
      width: '100%',
      marginBottom: normalize(24),
    },
    linkText: {
      flex: 1,
      fontSize: normalize(15),
      color: colors.textSecondary,
      marginRight: normalize(12),
    },
    copyIcon: {
      width: normalize(22),
      height: normalize(22),
      tintColor: colors.textSecondary,
    },
    shareBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1.5,
      borderColor: colors.primary,
      borderRadius: normalize(12),
      height: normalize(52),
      width: normalize(160),
    },
    shareIcon: {
      width: normalize(18),
      height: normalize(18),
      tintColor: colors.primary,
      marginRight: normalize(8),
    },
    shareText: {
      color: colors.primary,
      fontSize: normalize(15),
    },
    inputContainer: {
      position: 'relative',
      marginBottom: normalize(28),
      width: '100%',
    },
    input: {
      backgroundColor: colors.surfaceElevated,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: normalize(12),
      paddingHorizontal: normalize(16),
      paddingVertical: normalize(14),
      fontSize: normalize(15),
      color: colors.textPrimary,
      minHeight: normalize(56),
      maxHeight: normalize(100),
      fontFamily: 'Lato-Regular',
      textAlignVertical: 'top',
    },
    clearButton: {
      position: 'absolute',
      right: normalize(12),
      top: normalize(12),
      padding: normalize(4),
    },
    clearIcon: {
      width: normalize(18),
      height: normalize(18),
      tintColor: colors.textMuted,
    },
    buttonsContainer: {
      flexDirection: 'row',
      gap: normalize(12),
      width: '100%',
    },
    cancelButton: {
      flex: 1,
      borderWidth: 1.5,
      borderColor: colors.primary,
      borderRadius: normalize(12),
      height: normalize(48),
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.surface,
    },
    cancelButtonText: {
      color: colors.primary,
      fontSize: normalize(15),
    },
    joinButton: {
      flex: 1,
      backgroundColor: colors.primary,
      borderRadius: normalize(12),
      height: normalize(48),
      justifyContent: 'center',
      alignItems: 'center',
    },
    joinButtonDisabled: {
      backgroundColor: colors.border,
      opacity: 0.6,
    },
    joinButtonText: {
      color: colors.white,
      fontSize: normalize(15),
    },
  });
}

export function createBuzzLayoutPopoverStyles(colors: ThemeColors) {
  return StyleSheet.create({
    wrapper: { ...StyleSheet.absoluteFillObject },
    overlay: { ...StyleSheet.absoluteFillObject },
    fab: {
      position: 'absolute',
      right: normalize(20),
      bottom: normalize(20),
      width: normalize(56),
      height: normalize(56),
      borderRadius: normalize(28),
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 5,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      zIndex: 100,
    },
    fabActive: { backgroundColor: colors.secondary },
    plusIcon: { width: 24, height: 24, tintColor: colors.white },
    popoverCard: {
      position: 'absolute',
      right: normalize(20),
      bottom: normalize(80),
      backgroundColor: colors.surface,
      borderRadius: normalize(12),
      width: normalize(210),
      paddingVertical: normalize(4),
      zIndex: 101,
      ...Platform.select({
        ios: {
          shadowColor: colors.black,
          shadowOffset: { width: 0, height: 12 },
          shadowOpacity: 0.15,
          shadowRadius: 16,
        },
        android: { elevation: 12 },
      }),
    },
    menuItem: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: normalize(16),
    },
    menuIconFeather: { marginRight: 12 },
    menuText: { color: colors.textPrimary },
  });
}

export function createBuzzGreenRoomScreenStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.surface,
    },
    header: {
      flexDirection: 'row',
      gap: 3,
      alignItems: 'center',
      paddingHorizontal: 10,
      height: 56,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerIcon: {
      padding: 8,
    },
    scrollContent: {
      alignItems: 'center',
      paddingHorizontal: 24,
    },
    codeContainer: {
      marginVertical: 16,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    copyButton: {
      padding: 4,
    },
    buzzCode: {
      color: colors.textSecondary,
    },
    userCard: {
      backgroundColor: colors.surfaceElevated,
      borderRadius: 28,
      width: '80%',
      aspectRatio: 0.72,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 24,
      overflow: 'hidden',
    },
    userNameWrapper: {
      position: 'absolute',
      top: 16,
      left: 16,
      right: 16,
      zIndex: 10,
    },
    userNameWrapperVideo: {
      position: 'absolute',
      top: 16,
      left: 16,
      right: 16,
      borderRadius: 8,
      paddingVertical: 6,
      paddingHorizontal: 12,
      zIndex: 10,
    },
    userName: {
      fontSize: 18,
      color: colors.textSecondary,
      textAlign: 'center',
    },
    userNameVideo: {
      fontSize: 18,
      color: colors.white,
      textAlign: 'center',
    },
    previewContainer: {
      flex: 1,
      width: '100%',
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
    },
    avatarWrapper: {
      width: 140,
      height: 140,
      borderRadius: 70,
      overflow: 'hidden',
    },
    avatar: {
      width: '100%',
      height: '100%',
    },
    videoWrapper: {
      width: '100%',
      height: '100%',
      borderRadius: 28,
      overflow: 'hidden',
    },
    videoPreview: {
      width: '100%',
      height: '100%',
    },
    controlsOverlay: {
      position: 'absolute',
      bottom: 16,
      left: 0,
      right: 0,
      flexDirection: 'row',
      gap: 20,
      justifyContent: 'center',
      alignItems: 'center',
    },
    controlButton: {
      width: 52,
      height: 52,
      borderRadius: 26,
      backgroundColor: colors.white,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 1,
    },
    controlButtonOff: {
      backgroundColor: colors.textSecondary,
    },
    secondaryAction: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 4,
      height: 44,
      width: '100%',
      marginBottom: 12,
      gap: 10,
    },
    secondaryActionText: {
      fontSize: 14,
      color: colors.primary,
    },
    flipIcon: {
      transform: [{ scaleY: -1 }],
    },
    infoText: {
      fontSize: 14,
      color: colors.textSecondary,
      marginTop: 16,
      marginBottom: 24,
    },
    bottomSection: {
      paddingHorizontal: 24,
      paddingBottom: 16,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    joiningInfoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 20,
    },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    joiningInfoTitle: {
      fontSize: 16,
      color: colors.textPrimary,
      marginLeft: 12,
    },
    joinButton: {
      backgroundColor: colors.primary,
      borderRadius: 12,
      height: 64,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 16,
    },
    joinButtonDisabled: {
      opacity: 0.7,
    },
    joinButtonText: {
      fontSize: 16,
      color: colors.white,
    },
    accountSwitcher: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    miniAvatar: {
      width: 22,
      height: 22,
      borderRadius: 11,
    },
    emailLabel: {
      fontSize: 13,
      color: colors.textSecondary,
    },
    switchLink: {
      fontSize: 13,
      color: colors.primary,
    },
  });
}

export function createBuzzJoiningStyles(colors: ThemeColors) {
  return StyleSheet.create({
    mainContainer: { backgroundColor: colors.surface, flex: 1 },
    safeArea: { flex: 1 },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: normalize(16),
      height: normalize(56),
    },
    backButton: {
      width: normalize(40),
      height: normalize(40),
      justifyContent: 'center',
      alignItems: 'flex-start',
    },
    headerIcon: {
      width: normalize(24),
      height: normalize(24),
      tintColor: colors.textPrimary,
      objectFit: 'contain',
    },
    headerTitle: { fontSize: normalize(18), color: colors.textSecondary },
    headerPlaceholder: { width: normalize(24) },
    titleSection: {
      alignItems: 'center',
      marginTop: normalize(20),
      marginBottom: normalize(30),
    },
    meetingCode: { fontSize: normalize(26), color: colors.textPrimary },
    previewContainer: {
      alignItems: 'center',
      paddingHorizontal: normalize(20),
    },
    videoCard: {
      width: normalize(160),
      height: normalize(200),
      backgroundColor: colors.black,
      borderRadius: normalize(12),
      padding: normalize(12),
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    userName: {
      color: colors.white,
      fontSize: normalize(12),
      alignSelf: 'flex-start',
    },
    avatarWrapper: {
      width: normalize(90),
      height: normalize(90),
      borderRadius: normalize(45),
      overflow: 'hidden',
    },
    previewAvatar: { width: '100%', height: '100%' },
    controlsRow: { flexDirection: 'row', gap: normalize(40) },
    roundBtn: {
      width: normalize(34),
      height: normalize(34),
      borderRadius: normalize(17),
      backgroundColor: 'rgba(255,255,255,0.2)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    btnOff: { backgroundColor: colors.error },
    controlIcon: {
      width: normalize(18),
      height: normalize(18),
      tintColor: colors.white,
    },
    shareScreenBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: colors.primary,
      borderRadius: normalize(8),
      height: normalize(48),
      width: normalize(180),
      marginTop: normalize(24),
    },
    shareScreenIcon: {
      width: normalize(20),
      height: normalize(20),
      tintColor: colors.primary,
      marginRight: normalize(8),
    },
    shareScreenText: { color: colors.primary, fontSize: normalize(16) },
    statusText: {
      color: colors.textSecondary,
      fontSize: normalize(14),
      marginTop: normalize(16),
    },
    dividerFull: {
      height: 1,
      backgroundColor: colors.border,
      width: '100%',
      marginTop: normalize(40),
    },
    infoSection: { padding: normalize(24) },
    infoTitleRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: normalize(20),
    },
    infoTitleLabel: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: normalize(8),
    },
    infoIcon: {
      width: normalize(22),
      height: normalize(22),
      tintColor: colors.textPrimary,
    },
    infoTitleText: { fontSize: normalize(20), color: colors.textPrimary },
    labelSmall: {
      fontSize: normalize(14),
      color: colors.textSecondary,
      marginBottom: normalize(8),
    },
    linkBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.black,
      borderRadius: normalize(8),
      paddingHorizontal: normalize(16),
      height: normalize(52),
      marginBottom: normalize(30),
    },
    linkUrl: { flex: 1, color: colors.white, fontSize: normalize(14) },
    copyIconSmall: {
      width: normalize(20),
      height: normalize(20),
      tintColor: colors.white,
    },
    joinBtn: {
      backgroundColor: colors.primary,
      height: normalize(50),
      borderRadius: normalize(8),
      justifyContent: 'center',
      alignItems: 'center',
      width: normalize(110),
      alignSelf: 'center',
    },
    joinBtnText: { color: colors.white, fontSize: normalize(16) },
  });
}

export function createBuzzMeetingRoomStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.black },
    safeArea: { flex: 1, marginTop: normalize(20) },
    titleContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 8,
      paddingHorizontal: 10,
    },
    buzzCodeText: { fontSize: 16, color: colors.white, letterSpacing: 1 },
    headerButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: `${colors.primary}59`,
      justifyContent: 'center',
      alignItems: 'center',
    },
    centerContent: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    addMembersModalOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'rgba(0,0,0,0.35)',
    },
    addMembersModalContainer: {
      height: '90%',
      backgroundColor: colors.surface,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      overflow: 'hidden',
    },
  });
}

export function createBuzzCallControlStyles(colors: ThemeColors) {
  return StyleSheet.create({
    bottomContainer: {
      position: 'relative',
      paddingHorizontal: 15,
      paddingBottom: 30,
    },
    controlBar: {
      flexDirection: 'row',
      backgroundColor: colors.black,
      borderRadius: 35,
      paddingVertical: 12,
      justifyContent: 'space-around',
      alignItems: 'center',
    },
    iconCircle: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: 'rgba(255, 255, 255, 0.15)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    whiteIcon: {
      backgroundColor: colors.white,
    },
    endCallButton: {
      backgroundColor: colors.error,
      width: 56,
      height: 56,
      borderRadius: 28,
    },
    quickAccessRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 10,
      backgroundColor: colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      paddingHorizontal: 10,
      borderRadius: 25,
      height: 60,
      position: 'absolute',
      bottom: normalize(120),
      right: 10,
      left: 10,
    },
    emojiText: {
      fontSize: 22,
    },
    plusBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.categoryChip,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    inputIcon: {
      width: 24,
      height: 24,
      tintColor: colors.messageMeta,
    },
    container: { padding: 20 },
    card: {
      backgroundColor: colors.reactionBackground,
      borderRadius: 16,
      overflow: 'hidden',
    },
    menuItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 18,
    },
    menuText: { fontSize: 16, color: colors.textPrimary },
    divider: {
      height: 1,
      backgroundColor: colors.border,
      marginHorizontal: 18,
    },
    statusText: { fontSize: 13, color: colors.messageMeta, marginLeft: 6 },
  });
}

export function createBuzzParticipantStyles(colors: ThemeColors) {
  return StyleSheet.create({
    card: {
      height: 280,
      backgroundColor: colors.black,
      borderRadius: 20,
      margin: 8,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
      overflow: 'hidden',
    },
    videoWrapper: {
      width: '100%',
      height: '100%',
      position: 'absolute',
      top: 0,
      left: 0,
      zIndex: 10,
    },
    presentingBadge: {
      position: 'absolute',
      top: 12,
      right: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      backgroundColor: `${colors.primary}E6`,
      paddingHorizontal: 8,
      paddingVertical: 5,
      borderRadius: 6,
      zIndex: 16,
      maxWidth: '70%',
    },
    presentingText: {
      color: colors.white,
      fontSize: 11,
      fontWeight: '600',
    },
    videoUsernameBadge: {
      position: 'absolute',
      top: 12,
      left: 12,
      backgroundColor: 'rgba(0, 0, 0, 0.6)',
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 6,
      maxWidth: '80%',
      zIndex: 15,
    },
    videoUsername: {
      color: colors.white,
      fontSize: 12,
      fontWeight: '600',
      textTransform: 'capitalize',
    },
    avatarWrapper: {
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1,
    },
    cardAvatar: {
      width: 70,
      height: 70,
      borderRadius: 35,
    },
    avatarFallback: {
      width: 70,
      height: 70,
      borderRadius: 35,
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    avatarFallbackText: {
      color: colors.white,
      fontSize: 26,
      fontWeight: '700',
      textTransform: 'uppercase',
    },
    rtcSurfaceViewFull: {
      width: '100%',
      height: '100%',
    },
    audioVisualizerContainer: {
      position: 'relative',
      width: 110,
      height: 110,
      justifyContent: 'center',
      alignItems: 'center',
    },
    handRaiseBadge: {
      position: 'absolute',
      top: 10,
      right: 10,
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.lightYellow,
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 20,
    },
    micBadge: {
      position: 'absolute',
      bottom: 10,
      right: 10,
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: 'rgba(0, 0, 0, 0.55)',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 20,
    },
    micBadgeMuted: {
      backgroundColor: 'rgba(220, 38, 38, 0.75)',
    },
    ringingBadge: {
      position: 'absolute',
      bottom: 12,
      alignSelf: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.55)',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
      zIndex: 25,
    },
    ringingText: {
      color: colors.white,
      fontSize: 11,
      fontWeight: '600',
    },
    cardName: {
      color: colors.white,
      fontWeight: '600',
      textTransform: 'capitalize',
      textAlign: 'center',
    },
    singleParticipantContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      width: '100%',
    },
    twoParticipantContainer: {
      flex: 1,
      width: '100%',
    },
    twoParticipantScrollContent: {
      flexGrow: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 12,
    },
    twoParticipantItem: {
      width: '100%',
      alignItems: 'center',
    },
    twoParticipantItemSpacing: {},
    listContent: {
      justifyContent: 'center',
      alignItems: 'center',
      padding: 10,
    },
    loadingContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      justifyContent: 'center',
    },
    loadingText: { color: colors.white },
  });
}

export function createBuzzSidebarStyles(colors: ThemeColors) {
  return StyleSheet.create({
    modal: {
      margin: 0,
      justifyContent: 'flex-end',
      alignItems: 'flex-end',
    },
    container: {
      flex: 1,
      backgroundColor: colors.surface,
      paddingTop: Platform.OS === 'ios' ? 40 : 10,
      width: screenWidth,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 15,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    headerTitle: {
      fontSize: 18,
      color: colors.textPrimary,
    },
    headerSub: {
      fontSize: 12,
      color: colors.messageMeta,
    },
    closeCircle: {
      backgroundColor: colors.surfaceElevated,
      padding: 6,
      borderRadius: 20,
    },
    listContent: {
      padding: 20,
      paddingBottom: 40,
    },
    messageRow: {
      flexDirection: 'row',
      marginTop: 10,
    },
    avatarContainer: {
      marginRight: 12,
    },
    avatar: {
      width: 36,
      height: 36,
      borderRadius: 6,
    },
    avatarPlaceholder: {
      width: 36,
      height: 36,
      borderRadius: 6,
      backgroundColor: colors.categoryChip,
      justifyContent: 'center',
      alignItems: 'center',
    },
    avatarInitial: {
      fontSize: 14,
      color: colors.messageMeta,
    },
    messageContent: {
      flex: 1,
    },
    messageHeader: {
      flexDirection: 'row',
      alignItems: 'baseline',
      marginBottom: 4,
    },
    senderName: {
      fontSize: 15,
      color: colors.textPrimary,
      marginRight: 8,
    },
    timestamp: {
      fontSize: 11,
      color: colors.messageMeta,
    },
    messageText: {
      fontSize: 15,
      lineHeight: 20,
      color: colors.textPrimary,
    },
    actionsFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 8,
      flexWrap: 'wrap',
      gap: 8,
    },
    reactionsWrapper: {
      flexDirection: 'row',
      gap: 4,
    },
    reactionPill: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surfaceElevated,
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    reactionEmoji: { fontSize: 12 },
    reactionCount: { fontSize: 11, marginLeft: 2, color: colors.messageMeta },
    replyButton: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    replyButtonText: {
      fontSize: 13,
      color: colors.primary,
      marginLeft: 4,
    },
    threadPreview: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 8,
      backgroundColor: colors.threadBarBackground,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 4,
      alignSelf: 'flex-start',
    },
    threadText: {
      fontSize: 12,
      color: colors.primary,
      fontWeight: '600',
      marginRight: 4,
    },
    inputWrapper: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
      padding: 16,
      backgroundColor: colors.white,
    },
    typingIndicator: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 8,
    },
    typingText: {
      fontSize: 12,
      color: colors.messageMeta,
      fontStyle: 'italic',
    },
    replyingBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.surfaceElevated,
      padding: 8,
      borderRadius: 8,
      marginBottom: 10,
    },
    replyingBarContent: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    replyingToText: {
      fontSize: 13,
      marginLeft: 8,
      color: colors.textPrimary,
    },
    inputBox: {
      backgroundColor: colors.surfaceElevated,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      minHeight: 48,
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 8,
    },
    input: {
      flex: 1,
      fontSize: 15,
      maxHeight: 100,
      color: colors.textPrimary,
    },
    inputActions: {
      flexDirection: 'row',
      alignItems: 'center',
      marginLeft: 8,
      gap: 8,
    },
    attachmentIcon: {
      padding: 4,
    },
    sendCircle: {
      backgroundColor: colors.primary,
      width: 32,
      height: 32,
      borderRadius: 16,
      justifyContent: 'center',
      alignItems: 'center',
    },
    participantRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 10,
      backgroundColor: colors.bgSecondary,
      borderRadius: 12,
      padding: 12,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
      elevation: 2,
    },
    statusIcon: {
      marginRight: 8,
    },
    infoContainer: {
      flex: 1,
    },
    nameText: {
      fontSize: 15,
      color: colors.textPrimary,
      marginBottom: 2,
    },
    roleText: {
      fontSize: 12,
      color: colors.messageMeta,
    },
    actionsContainer: {
      flexDirection: 'row',
      alignItems: 'center',
    },
  });
}

export function createBuzzAddMembersStyles(colors: ThemeColors) {
  return StyleSheet.create({
    navHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 15,
      backgroundColor: colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    navTitleCenter: { alignItems: 'center' },
    navTitle: { fontSize: 17, fontWeight: '700', color: colors.textPrimary },
    navActionText: { fontSize: 16, color: colors.primary },
    searchSection: {
      backgroundColor: colors.surface,
      paddingHorizontal: 20,
      paddingVertical: 12,
    },
    searchWrapper: {
      flexDirection: 'row',
      backgroundColor: colors.reactionBackground,
      borderRadius: 12,
      paddingHorizontal: 12,
      alignItems: 'center',
      height: 44,
    },
    input: {
      flex: 1,
      fontSize: 16,
      color: colors.textPrimary,
      paddingVertical: 0,
    },
    contentContainer: { flex: 1, position: 'relative' },
    scrollContent: { paddingLeft: 20, paddingRight: 36, paddingBottom: 50 },
    sectionHeader: {
      fontSize: 14,
      color: colors.messageMeta,
      marginTop: 20,
      marginBottom: 8,
    },
    groupCard: { backgroundColor: colors.surface },
    cardTop: { borderTopLeftRadius: 16, borderTopRightRadius: 16 },
    cardBottom: { borderBottomLeftRadius: 16, borderBottomRightRadius: 16 },
    userRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 14,
      paddingHorizontal: 0,
    },
    rowBorder: { borderBottomWidth: 1, borderBottomColor: colors.border },
    userInfo: { flexDirection: 'row', alignItems: 'center' },
    avatar: { width: 40, height: 40, borderRadius: 20, marginRight: 12 },
    userName: { fontSize: 15, fontWeight: '600', color: colors.textPrimary },
    userRole: { fontSize: 13, color: colors.messageMeta },
    radioCircle: {
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
    },
    radioActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    alphabetSidebar: {
      position: 'absolute',
      right: 8,
      top: 0,
      bottom: 0,
      width: 20,
      justifyContent: 'flex-start',
      alignItems: 'center',
      paddingTop: 6,
      zIndex: 10,
    },
    alphabetText: {
      fontSize: 10,
      color: colors.primary,
      fontWeight: '600',
      paddingVertical: 1.5,
    },
    footerLoader: {
      paddingVertical: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyStateContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 32,
    },
    emptyStateText: {
      color: colors.messageMeta,
      fontSize: 16,
      textAlign: 'center',
    },
    searchLabel: {
      color: colors.messageMeta,
      marginRight: 8,
    },
    navActionBold: {
      color: colors.primary,
      fontWeight: '700',
    },
    navActionRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    navActionLoading: {
      marginRight: 6,
    },
  });
}

export function createBuzzTimeoutStyles(colors: ThemeColors) {
  return StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContainer: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      paddingVertical: 32,
      paddingHorizontal: 24,
      maxWidth: 440,
      width: screenWidth - 40,
      alignItems: 'center',
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 8,
    },
    timerCircle: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: colors.surfaceElevated,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 24,
    },
    timerText: {
      fontSize: 18,
      fontWeight: '600',
      color: colors.primary,
    },
    modalTitle: {
      fontSize: 22,
      fontWeight: '400',
      color: colors.textPrimary,
      textAlign: 'center',
      marginBottom: 32,
    },
    message: {
      fontSize: 14,
      lineHeight: 20,
      color: colors.textSecondary,
      textAlign: 'center',
      marginBottom: 24,
    },
    modalButtonRow: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 8,
      width: '100%',
    },
    modalButton: {
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 4,
      minHeight: 40,
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalLeaveButton: {
      backgroundColor: colors.surfaceElevated,
    },
    modalLeaveButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.primary,
    },
    stayButton: {
      backgroundColor: colors.surfaceElevated,
    },
    stayButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.primary,
    },
    container: {
      position: 'absolute',
      top: 10,
      left: 16,
      right: 16,
      zIndex: 9999,
      borderRadius: 12,
      backgroundColor: colors.surface,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 10,
      overflow: 'hidden',
    },
    content: {
      padding: 16,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginBottom: 16,
    },
    iconContainer: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: 'rgba(239, 68, 68, 0.1)',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    textContainer: {
      flex: 1,
    },
    title: {
      fontSize: 16,
      color: colors.textPrimary,
      marginBottom: 2,
    },
    subtitle: {
      fontSize: 13,
      color: colors.textMuted,
    },
    closeButton: {
      padding: 4,
    },
    buttonRow: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 8,
    },
    button: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 6,
      minHeight: 36,
      justifyContent: 'center',
      alignItems: 'center',
    },
    dismissButton: {
      backgroundColor: colors.transparent,
    },
    dismissButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.primary,
    },
    leaveButton: {
      backgroundColor: colors.primary,
    },
    leaveButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.white,
    },
    progressBarBackground: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      height: 4,
      backgroundColor: `${colors.primary}1A`,
      borderBottomLeftRadius: 12,
      borderBottomRightRadius: 12,
    },
    progressBarFill: {
      height: '100%',
      backgroundColor: colors.primary,
      borderBottomLeftRadius: 12,
    },
  });
}

export function createBuzzRecordingStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      position: 'absolute',
      top: 70,
      left: 16,
      zIndex: 100,
    },
    badge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      borderRadius: 999,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.1)',
      paddingHorizontal: 12,
      height: 36,
      gap: 8,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 8,
    },
    badgeExpanded: {
      gap: 12,
    },
    dotContainer: {
      width: 10,
      height: 10,
      justifyContent: 'center',
      alignItems: 'center',
    },
    pingDot: {
      position: 'absolute',
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.error,
    },
    solidDot: {
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.error,
    },
    label: {
      color: colors.white,
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 2,
      textTransform: 'uppercase',
    },
    stopButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: 'rgba(255, 255, 255, 0.1)',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    stopLabel: {
      color: 'rgba(255, 255, 255, 0.9)',
      fontSize: 10,
      fontWeight: '700',
      textTransform: 'uppercase',
    },
  });
}

export function createBuzzGreenRoomComponentStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.topNavigation,
    },
    gradientOverlay: {
      flex: 1,
      backgroundColor: 'rgba(186, 186, 251, 0.15)',
    },
    contentWrapper: {
      flex: 1,
      paddingHorizontal: normalize(20),
      paddingTop: normalize(40),
      paddingBottom: normalize(30),
    },
    headerSection: {
      alignItems: 'center',
    },
    headerBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.white,
      paddingHorizontal: normalize(16),
      paddingVertical: normalize(8),
      borderRadius: normalize(20),
      marginBottom: normalize(12),
      ...Platform.select({
        ios: {
          shadowColor: colors.secondary,
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.15,
          shadowRadius: 8,
        },
        android: {
          elevation: 6,
        },
      }),
    },
    liveDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.online,
      marginRight: 8,
    },
    headerBadgeText: {
      fontSize: normalize(12),
      color: colors.textMain,
    },
    buzzTitle: {
      fontSize: normalize(28),
      color: colors.textMain,
      marginBottom: normalize(8),
      textAlign: 'center',
    },
    participantsInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    participantsText: {
      fontSize: normalize(14),
      color: colors.textSecondary,
    },
    previewSection: {
      flex: 1,
      justifyContent: 'center',
      marginBottom: normalize(20),
    },
    previewCard: {
      backgroundColor: colors.white,
      borderRadius: normalize(24),
      overflow: 'hidden',
      ...Platform.select({
        ios: {
          shadowColor: colors.secondary,
          shadowOffset: { width: 0, height: 8 },
          shadowOpacity: 0.2,
          shadowRadius: 16,
        },
        android: {
          elevation: 10,
        },
      }),
    },
    cornerDecor: {
      position: 'absolute',
      width: normalize(30),
      height: normalize(30),
      borderColor: colors.secondary,
      borderWidth: 3,
      zIndex: 10,
    },
    topLeftCorner: {
      top: normalize(12),
      left: normalize(12),
      borderRightWidth: 0,
      borderBottomWidth: 0,
      borderTopLeftRadius: normalize(8),
    },
    topRightCorner: {
      top: normalize(12),
      right: normalize(12),
      borderLeftWidth: 0,
      borderBottomWidth: 0,
      borderTopRightRadius: normalize(8),
    },
    bottomLeftCorner: {
      bottom: normalize(72),
      left: normalize(12),
      borderRightWidth: 0,
      borderTopWidth: 0,
      borderBottomLeftRadius: normalize(8),
    },
    bottomRightCorner: {
      bottom: normalize(72),
      right: normalize(12),
      borderLeftWidth: 0,
      borderTopWidth: 0,
      borderBottomRightRadius: normalize(8),
    },
    videoPreviewContainer: {
      height: screenHeight * 0.45,
      backgroundColor: colors.secondary,
      position: 'relative',
    },
    videoPreview: {
      width: '100%',
      height: '100%',
    },
    avatarContainer: {
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.secondary,
    },
    avatarImage: {
      width: normalize(120),
      height: normalize(120),
      borderRadius: normalize(60),
      borderWidth: 4,
      borderColor: colors.white,
    },
    avatarPlaceholder: {
      fontSize: normalize(48),
      color: colors.white,
    },
    statusOverlay: {
      position: 'absolute',
      bottom: normalize(16),
      left: normalize(16),
    },
    statusBadge: {
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      paddingHorizontal: normalize(12),
      paddingVertical: normalize(6),
      borderRadius: normalize(8),
    },
    statusBadgeText: {
      fontSize: normalize(14),
      color: colors.white,
    },
    mediaStatusContainer: {
      position: 'absolute',
      top: normalize(16),
      right: normalize(16),
      flexDirection: 'row',
      gap: 8,
    },
    mediaStatusBadge: {
      width: normalize(36),
      height: normalize(36),
      borderRadius: normalize(18),
      backgroundColor: `${colors.primary}E6`,
      justifyContent: 'center',
      alignItems: 'center',
    },
    mediaStatusBadgeMuted: {
      backgroundColor: 'rgba(255, 59, 48, 0.9)',
    },
    deviceControlsRow: {
      flexDirection: 'row',
      backgroundColor: colors.bgSecondary,
      paddingVertical: normalize(16),
      paddingHorizontal: normalize(20),
    },
    deviceControl: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      paddingVertical: normalize(8),
      borderRadius: normalize(8),
    },
    deviceControlActive: {
      backgroundColor: 'rgba(255, 59, 48, 0.1)',
    },
    deviceControlText: {
      fontSize: normalize(14),
      color: colors.secondary,
    },
    deviceControlTextActive: {
      color: colors.error,
    },
    deviceControlDivider: {
      width: 1,
      height: '100%',
      backgroundColor: colors.border,
      marginHorizontal: normalize(12),
    },
    infoCardsSection: {
      flexDirection: 'row',
      gap: 12,
      marginBottom: normalize(20),
    },
    infoCard: {
      flex: 1,
      flexDirection: 'row',
      backgroundColor: colors.white,
      padding: normalize(12),
      borderRadius: normalize(12),
      alignItems: 'center',
      ...Platform.select({
        ios: {
          shadowColor: colors.secondary,
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.08,
          shadowRadius: 8,
        },
        android: {
          elevation: 3,
        },
      }),
    },
    infoCardIcon: {
      width: normalize(40),
      height: normalize(40),
      borderRadius: normalize(20),
      backgroundColor: colors.secondaryforeground,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: normalize(10),
    },
    infoCardContent: {
      flex: 1,
    },
    infoCardTitle: {
      fontSize: normalize(12),
      color: colors.textMain,
      marginBottom: 2,
    },
    infoCardDescription: {
      fontSize: normalize(10),
      color: colors.textSecondary,
    },
    ctaSection: {
      alignItems: 'center',
      width: '100%',
    },
    ctaRow: {
      width: '100%',
      flexDirection: 'row',
      gap: normalize(10),
    },
    ctaButtonWrap: {
      flex: 1,
    },
    joinButton: {
      width: '100%',
      minHeight: normalize(52),
      borderRadius: normalize(16),
      overflow: 'hidden',
      ...Platform.select({
        ios: {
          shadowColor: colors.secondary,
          shadowOffset: { width: 0, height: 8 },
          shadowOpacity: 0.3,
          shadowRadius: 12,
        },
        android: {
          elevation: 8,
        },
      }),
    },
    joinButtonGradient: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: normalize(14),
      paddingHorizontal: normalize(12),
      gap: 8,
      backgroundColor: colors.secondary,
    },
    joinButtonText: {
      fontSize: normalize(15),
      color: colors.white,
    },
    goHomeButton: {
      minHeight: normalize(52),
      borderRadius: normalize(12),
      borderWidth: 1,
      borderColor: colors.secondary,
      backgroundColor: 'rgba(255,255,255,0.9)',
      paddingHorizontal: normalize(16),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    goHomeText: {
      color: colors.secondary,
      fontSize: normalize(14),
    },
    helperText: {
      fontSize: normalize(12),
      color: colors.textSecondary,
      textAlign: 'center',
    },
    decorativeElements: {
      position: 'absolute',
      width: '100%',
      height: '100%',
      pointerEvents: 'none',
    },
    floatingDot1: {
      position: 'absolute',
      top: '15%',
      right: '10%',
      width: normalize(60),
      height: normalize(60),
      borderRadius: normalize(30),
      backgroundColor: `${colors.primary}1A`,
    },
    floatingDot2: {
      position: 'absolute',
      bottom: '30%',
      left: '5%',
      width: normalize(80),
      height: normalize(80),
      borderRadius: normalize(40),
      backgroundColor: 'rgba(186, 186, 251, 0.15)',
    },
    floatingDot3: {
      position: 'absolute',
      top: '50%',
      right: '5%',
      width: normalize(40),
      height: normalize(40),
      borderRadius: normalize(20),
      backgroundColor: `${colors.primary}14`,
    },
  });
}

export function createWelcomeScreenStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.surface,
      paddingHorizontal: 25,
    },
    topSection: {
      flex: 2,
      justifyContent: 'center',
      alignItems: 'center',
    },
    logoContainer: {
      alignItems: 'center',
    },
    logo: {
      width: 100,
      height: 100,
      marginRight: 10,
    },
    brandName: {
      fontSize: 42,
      letterSpacing: -1.5,
      color: colors.textPrimary,
    },
    slogan: {
      fontSize: 17,
      textAlign: 'center',
      lineHeight: 24,
      color: colors.textSecondary,
      paddingHorizontal: 40,
    },
    middleSection: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    welcomeTitle: {
      fontSize: 32,
      marginBottom: 12,
      color: colors.textPrimary,
    },
    legalText: {
      fontSize: 14,
      textAlign: 'center',
      color: colors.textSecondary,
      lineHeight: 20,
    },
    linkText: {
      color: colors.primary,
    },
    bottomSection: {
      flex: 1,
      justifyContent: 'flex-end',
      paddingBottom: 20,
    },
    primaryBtn: {
      backgroundColor: colors.primary,
      height: 56,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 14,
    },
    primaryBtnText: {
      color: colors.white,
      fontSize: 16,
    },
    secondaryBtn: {
      height: 56,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    secondaryBtnText: {
      color: colors.primary,
      fontSize: 16,
    },
  });
}

export function createBuzzMinimizedWidgetStyles(colors: ThemeColors) {
  const { width: screenWidth } = Dimensions.get('window');

  return StyleSheet.create({
    androidContainer: {
      position: 'absolute',
      backgroundColor: colors.secondary,
      borderRadius: normalize(20),
      zIndex: 999,
      minWidth: normalize(200),
      maxWidth: screenWidth - normalize(32),
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.15)',
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 10,
      elevation: 12,
      paddingHorizontal: normalize(10),
      paddingVertical: normalize(8),
    },
    androidHeader: {
      paddingBottom: normalize(8),
    },
    androidHeaderTapArea: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: normalize(6),
    },
    activeDot: {
      width: normalize(8),
      height: normalize(8),
      borderRadius: normalize(4),
      backgroundColor: colors.online,
    },
    androidTitle: {
      flex: 1,
      color: colors.white,
      fontSize: normalize(12),
    },
    androidControls: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: normalize(8),
    },
    androidControlButton: {
      width: normalize(40),
      height: normalize(40),
      borderRadius: normalize(20),
      backgroundColor: 'rgba(255,255,255,0.15)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    androidControlButtonActive: {
      backgroundColor: colors.white,
    },
    androidEndCallButton: {
      width: normalize(44),
      height: normalize(44),
      borderRadius: normalize(22),
      backgroundColor: colors.error,
    },
    emojiButtonText: {
      fontSize: normalize(18),
    },
  });
}

export function createBuzzFloatingEmojiStyles(colors: ThemeColors) {
  return StyleSheet.create({
    overlay: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 90,
    },
    emojiContainer: {
      position: 'absolute',
      alignItems: 'center',
    },
    emojiText: {
      fontSize: 58,
      lineHeight: 64,
    },
    nameTag: {
      marginTop: 4,
      fontSize: 14,
      color: colors.white,
      backgroundColor: 'rgba(0,0,0,0.6)',
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 5,
      overflow: 'hidden',
    },
  });
}
