import { Dimensions, Platform, StyleSheet } from 'react-native';
import { normalize } from '@/utils/normalize';
import type { ThemeColors } from './types';

const { width, height } = Dimensions.get('window');

export function createMessageActionStyles(colors: ThemeColors) {
  return StyleSheet.create({
    pinnedHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingHorizontal: 20,
      paddingVertical: 15,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    avatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      marginRight: 12,
      borderWidth: 0.5,
      borderColor: colors.border,
    },
    textContainer: { flex: 1 },
    reactionContainer: {
      paddingVertical: 15,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.reactionBackground,
    },
    reactionScroll: {
      flex: 1,
      paddingHorizontal: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    plusBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.categoryChip,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    actionItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      paddingHorizontal: 20,
    },
    iconWrapper: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: colors.categoryChip,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 15,
    },
    icon: { width: 20, height: 20, tintColor: colors.textPrimary },
    label: { color: colors.textPrimary },
    messageMeta: { color: colors.messageMeta, marginTop: 2 },
    destructiveIconWrapper: { backgroundColor: `${colors.error}1A` },
    destructiveIcon: { tintColor: colors.error },
    destructiveLabel: { color: colors.error },
    inputIcon: { width: 24, height: 24, tintColor: colors.iconDefault },
    deleteConfirmContainer: { paddingVertical: 10 },
    deleteTitle: { paddingHorizontal: 20, color: colors.textPrimary },
  });
}

export function createEmojiPickerTheme(colors: ThemeColors) {
  return {
    knob: colors.border,
    container: colors.surface,
    header: colors.textSecondary,
    skinTonesContainer: colors.reactionBackground,
    category: {
      icon: colors.iconDefault,
      iconActive: colors.primary,
      container: colors.reactionBackground,
      containerActive: colors.surface,
    },
    search: {
      text: colors.textPrimary,
      placeholder: colors.textMuted,
      icon: colors.iconMuted,
      background: colors.reactionBackground,
    },
    customButton: {
      icon: colors.iconDefault,
      iconPressed: colors.primary,
      background: colors.reactionBackground,
      backgroundPressed: colors.categoryChip,
    },
    emoji: {
      selected: colors.reactionBackground,
    },
  };
}

export function createEmojiPickerStyles(colors: ThemeColors) {
  return {
    container: {
      backgroundColor: colors.surface,
    },
    header: {
      backgroundColor: colors.surface,
    },
    searchBar: {
      container: {
        backgroundColor: colors.reactionBackground,
      },
    },
    category: {
      container: {
        backgroundColor: colors.reactionBackground,
      },
    },
  };
}

export function createForwardModalStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.white,
    },
    header: {
      height: 52,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    cancelText: { color: colors.primary },
    headerTitle: { color: colors.textPrimary },
    sendText: { color: colors.primary },
    sendTextDisabled: { color: colors.iconMuted },
    body: {
      flex: 1,
      paddingHorizontal: 16,
      paddingTop: 8,
    },
    forwardToSection: {
      position: 'relative',
      zIndex: 20,
    },
    forwardToInput: {
      fontSize: 17,
      color: colors.textPrimary,
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    dropdown: {
      position: 'absolute',
      top: 52,
      left: 0,
      right: 0,
      backgroundColor: colors.white,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 8,
      maxHeight: 280,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 12,
      elevation: 8,
      zIndex: 30,
    },
    dropdownList: { maxHeight: 280 },
    dropdownLoading: {
      paddingVertical: 24,
      alignItems: 'center',
    },
    dropdownEmpty: {
      paddingVertical: 20,
      paddingHorizontal: 16,
    },
    dropdownEmptyText: { color: colors.textSecondary },
    destinationRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 14,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.surfaceElevated,
    },
    channelIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 8,
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 12,
    },
    avatarWrap: {
      width: 36,
      height: 36,
      marginRight: 12,
      position: 'relative',
    },
    avatar: {
      width: 36,
      height: 36,
      borderRadius: 8,
    },
    avatarPlaceholder: {
      backgroundColor: colors.reactionBackground,
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarInitial: { color: colors.textPrimary },
    statusDot: {
      position: 'absolute',
      right: -1,
      bottom: -1,
      width: 10,
      height: 10,
      borderRadius: 5,
      borderWidth: 2,
      borderColor: colors.white,
    },
    destinationTextWrap: {
      flex: 1,
      minWidth: 0,
    },
    destinationLabel: { color: colors.textPrimary },
    destinationSubtitle: {
      color: colors.textSecondary,
      marginTop: 2,
    },
    noteInput: {
      fontSize: 17,
      color: colors.textPrimary,
      paddingVertical: 14,
      minHeight: 48,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    previewCard: {
      marginTop: 18,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
      padding: 14,
      backgroundColor: colors.white,
    },
    previewHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    previewAuthorRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      minWidth: 0,
    },
    previewAvatar: {
      width: 24,
      height: 24,
      borderRadius: 6,
      marginRight: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.reactionBackground,
    },
    previewAuthorName: {
      color: colors.textPrimary,
      flexShrink: 1,
    },
    previewDate: {
      color: colors.textSecondary,
      marginLeft: 8,
    },
    previewMessage: {
      color: colors.textPrimary,
      lineHeight: 22,
      fontSize: 15,
    },
    previewMention: { color: colors.primary },
    previewLink: {
      color: colors.primary,
      textDecorationLine: 'underline',
    },
    previewImage: {
      width: '100%',
      height: 180,
      borderRadius: 8,
      marginTop: 10,
      backgroundColor: colors.surfaceElevated,
    },
    previewFileRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 4,
      gap: 10,
    },
    previewFileIcon: {
      width: 36,
      height: 36,
      borderRadius: 6,
      alignItems: 'center',
      justifyContent: 'center',
    },
    previewFileLabel: { color: colors.white },
    previewFileName: {
      flex: 1,
      color: colors.textPrimary,
    },
  });
}

export function createMentionSheetStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      maxHeight: 240,
      backgroundColor: colors.lightBlue,
      borderTopWidth: 1,
      borderTopColor: colors.border,
    },
    header: {
      paddingHorizontal: 16,
      paddingTop: 10,
      paddingBottom: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerHint: {
      color: colors.messageMeta,
      marginTop: 2,
    },
    list: { maxHeight: 190 },
    scrollContent: { paddingBottom: 8 },
    memberRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    avatarContainer: { position: 'relative' },
    avatar: {
      width: 32,
      height: 32,
      borderRadius: 16,
    },
    onlineBadge: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.online,
      borderWidth: 2,
      borderColor: colors.white,
    },
    offlineBadge: {
      position: 'absolute',
      bottom: 0,
      right: 0,
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: colors.offline,
      borderWidth: 2,
      borderColor: colors.white,
    },
    memberInfo: {
      marginLeft: 12,
      flex: 1,
    },
    channelMentionBadge: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: colors.channelMentionBackground,
      alignItems: 'center',
      justifyContent: 'center',
    },
    channelMentionBadgeText: {
      color: colors.channelMentionForeground,
    },
    channelMentionLabel: {
      color: colors.channelMentionForeground,
    },
    statusText: { color: colors.messageMeta },
    emptyContainer: {
      padding: 24,
      alignItems: 'center',
    },
    emptyText: { color: colors.messageMeta },
    sheetBackground: {
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
    },
    indicator: {
      backgroundColor: colors.border,
      width: 40,
    },
    headerSection: {
      alignItems: 'center',
      paddingTop: 10,
      backgroundColor: colors.surface,
      paddingBottom: 20,
    },
    avatarWrapper: {
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
      marginBottom: 12,
    },
    onlineStatus: {
      position: 'absolute',
      bottom: -5,
      right: -5,
      width: 26,
      height: 26,
      borderRadius: 13,
      borderWidth: 4,
      borderColor: colors.white,
    },
    userName: { fontSize: 26, color: colors.textPrimary },
    userTitle: {
      fontSize: 15,
      color: colors.messageMeta,
      marginTop: 4,
      letterSpacing: 0.5,
    },
    statusBubble: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surfaceElevated,
      paddingHorizontal: 18,
      paddingVertical: 10,
      borderRadius: 24,
      marginTop: 18,
      maxWidth: '85%',
      borderWidth: 1,
      borderColor: colors.border,
      overflow: 'hidden',
    },
    statusEmoji: { fontSize: 18, marginRight: 8 },
    usernameText: {
      color: colors.textPrimary,
      marginBottom: 4,
    },
    actionGrid: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 30,
      width: '100%',
      marginTop: 30,
    },
    actionItem: { alignItems: 'center' },
    circleAction: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    actionIconCircle: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.topNavigation,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 8,
    },
    circleActionText: {
      color: colors.primary,
      fontWeight: '600',
    },
    actionLabel: { color: colors.primary },
    divider: {
      height: 10,
      backgroundColor: colors.surfaceElevated,
    },
    infoSection: {
      backgroundColor: colors.surface,
      padding: 16,
    },
    sectionTitle: {
      color: colors.messageMeta,
      marginBottom: 12,
    },
    aboutRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    aboutContent: { flex: 1 },
    dateText: { color: colors.messageMeta },
    listSection: { backgroundColor: colors.surface },
    listItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 14,
    },
    listItemText: {
      color: colors.textPrimary,
      marginLeft: 20,
    },
    listItemContent: {
      marginLeft: 20,
      flex: 1,
    },
    subText: {
      color: colors.messageMeta,
      marginTop: 2,
    },
  });
}

export function createReactionDetailsStyles(colors: ThemeColors) {
  return StyleSheet.create({
    headerBlock: {
      paddingBottom: 4,
    },
    sheetTitle: {
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 8,
      fontSize: 18,
      color: colors.textPrimary,
    },
    heroEmojiWrap: {
      alignSelf: 'center',
      backgroundColor: colors.surfaceElevated,
      borderRadius: 16,
      paddingVertical: 10,
      paddingHorizontal: 16,
      marginBottom: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    heroEmoji: {
      fontSize: 40,
      textAlign: 'center',
    },
    body: {
      flex: 1,
    },
    tabContainer: {
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    tabList: {
      paddingHorizontal: 8,
    },
    tabItem: {
      paddingVertical: 12,
      paddingHorizontal: 14,
      position: 'relative',
    },
    tabText: {
      color: colors.messageMeta,
      fontSize: 15,
    },
    activeTabText: {
      color: colors.primary,
      fontWeight: 'bold',
    },
    tabIndicator: {
      position: 'absolute',
      bottom: 0,
      left: 14,
      right: 14,
      height: 3,
      backgroundColor: colors.primary,
      borderRadius: 2,
    },
    list: {
      flex: 1,
    },
    sheetList: { paddingBottom: 40, flexGrow: 1 },
    loadingState: {
      paddingVertical: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyState: {
      paddingVertical: 40,
      alignItems: 'center',
    },
    emptyText: {
      color: colors.messageMeta,
      fontSize: 14,
    },
    userReactionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    sheetAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.surfaceElevated,
    },
    sheetAvatarFallback: {
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.reactionBackground,
      borderWidth: 1,
      borderColor: colors.border,
    },
    sheetAvatarInitial: {
      color: colors.primary,
    },
    sheetUserInfo: {
      flex: 1,
      marginLeft: 14,
      minWidth: 0,
    },
    sheetUserName: {
      color: colors.textPrimary,
    },
    sheetUserMeta: {
      color: colors.messageMeta,
      marginTop: 2,
    },
    sheetEmoji: { fontSize: 22 },
  });
}

export function createThreadItemStyles(colors: ThemeColors) {
  return StyleSheet.create({
    rowContainer: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingLeft: 10,
      paddingRight: 10,
      marginBottom: 20,
      width: '100%',
    },
    sentRow: { alignSelf: 'flex-end', paddingRight: 10 },
    messageColumn: { flex: 1, minWidth: 0 },
    groupAvatarContainer: { marginRight: 5, flexShrink: 0 },
    threadStatusIcon: { marginRight: 4, alignSelf: 'center', flexShrink: 0 },
    groupSenderAvatar: {
      width: 35,
      height: 35,
      borderRadius: 50,
      borderWidth: 2,
      borderColor: colors.primary,
    },
    senderNameLabel: { paddingHorizontal: 8, paddingTop: 4, paddingBottom: 2 },
    senderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      minWidth: 0,
    },
    messageWrapper: {
      width: '100%',
      maxWidth: '100%',
      marginTop: -3,
      flexShrink: 1,
    },
    messageTextContainer: {
      width: '100%',
      minWidth: 0,
      flexShrink: 1,
      paddingHorizontal: 8,
      // paddingVertical: 4,
    },
    sentWrapper: { alignSelf: 'flex-end' },
    receivedWrapper: { alignSelf: 'flex-start' },
    bubble: {
      padding: 4,
      borderRadius: 12,
      elevation: 0.5,
      shadowColor: colors.black,
      shadowOpacity: 0.04,
      shadowRadius: 1,
    },
    sentBubble: {
      backgroundColor: colors.chatSentBubble,
      borderTopRightRadius: 2,
    },
    receivedBubble: {
      backgroundColor: colors.chatReceivedBubble,
      borderTopLeftRadius: 2,
    },
    mediaContainer: {
      position: 'relative',
      maxWidth: '100%',
      alignSelf: 'flex-start',
    },
    videoWrapper: {
      width: '100%',
      maxWidth: width * 0.75,
      height: 220,
      borderRadius: 10,
      overflow: 'hidden',
      backgroundColor: colors.black,
    },
    verticalMediaStack: {
      flexDirection: 'column',
      gap: 4,
      marginBottom: 2,
      marginTop: 5,
      backgroundColor: colors.border,
      borderRadius: 10,
      maxWidth: '100%',
      alignSelf: 'flex-start',
    },
    mediaImage: {
      width: width * 0.75,
      height: 220,
      borderRadius: 10,
      borderWidth: 0.5,
      borderColor: colors.border,
    },
    videoPlayOverlay: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0,0,0,0.1)',
    },
    playIconCircle: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      paddingLeft: 4,
    },
    videoDurationLabel: {
      position: 'absolute',
      bottom: 8,
      left: 8,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: 'rgba(0,0,0,0.5)',
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 10,
    },
    mediaTimeOverlay: {
      position: 'absolute',
      bottom: 8,
      right: 8,
      backgroundColor: 'rgba(0,0,0,0.4)',
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 10,
      flexDirection: 'row',
      alignItems: 'center',
    },
    mediaTimeText: { color: colors.white },
    receiptIconSmall: {
      width: 14,
      height: 14,
      marginLeft: 3,
      tintColor: colors.lightBlue,
    },
    voiceContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      maxWidth: width * 0.65,
      paddingVertical: 10,
      paddingHorizontal: 6,
    },
    playBtn: {
      width: 30,
      height: 30,
      justifyContent: 'center',
      alignItems: 'center',
    },
    playIcon: { color: colors.messageMeta },
    waveformContainer: {
      flex: 1,
      height: 35,
      justifyContent: 'center',
      marginHorizontal: 8,
    },
    waveformLine: {
      height: 2,
      backgroundColor: colors.waveformInactive,
      width: '100%',
      borderRadius: 1,
    },
    playbackThumb: {
      width: 10,
      height: 10,
      borderRadius: 5,
      position: 'absolute',
      left: '0%',
    },
    voiceDuration: {
      position: 'absolute',
      bottom: -2,
      left: 0,
      color: colors.messageMeta,
    },
    voiceAvatarContainer: {
      position: 'relative',
      width: 36,
      height: 36,
      marginLeft: 4,
    },
    voiceAvatar: { width: 36, height: 36, borderRadius: 18 },
    micBadge: {
      position: 'absolute',
      bottom: -2,
      right: -2,
      width: 14,
      height: 14,
      borderRadius: 7,
      justifyContent: 'center',
      alignItems: 'center',
    },
    miniMic: { width: 8, height: 8, tintColor: colors.white },
    complexFileWrapper: {
      backgroundColor: colors.reactionBackground,
      borderRadius: 8,
      padding: 10,
      width: '100%',
      maxWidth: width * 0.65,
      marginBottom: 4,
      alignSelf: 'flex-start',
    },
    fileMainRow: { flexDirection: 'row', alignItems: 'center' },
    fileIconBox: {
      width: 42,
      height: 42,
      borderRadius: 6,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 1,
    },
    fileExtText: { color: colors.white, fontWeight: 'bold', fontSize: 10 },
    fileInfo: { flex: 1, marginLeft: 12 },
    fileNameText: {
      fontSize: 14,
      color: colors.textPrimary,
      fontWeight: '500',
    },
    fileMetaText: { color: colors.messageMeta, marginTop: 2 },
    replyContainer: {
      backgroundColor: colors.reactionBackground,
      padding: 8,
      borderRadius: 8,
      borderLeftWidth: 4,
      borderLeftColor: colors.primary,
      marginBottom: 5,
      marginHorizontal: 4,
      marginTop: 4,
    },
    messageText: {
      color: colors.textPrimary,
      fontSize: 15,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    messageFooter: {
      flexDirection: 'row',
      alignSelf: 'flex-end',
      alignItems: 'center',
      marginTop: 2,
      paddingRight: 8,
      paddingBottom: 4,
    },
    timeText: { color: colors.messageMeta, marginLeft: 8, flexShrink: 0 },
    receiptIcon: {
      width: 16,
      height: 16,
      marginLeft: 4,
      tintColor: colors.lightBlue,
    },
    dateHeader: {
      alignSelf: 'center',
      backgroundColor: colors.dateHeaderBackground,
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 8,
      marginVertical: 15,
    },
    dateText: {
      color: colors.iconDefault,
      fontSize: 12,
      fontWeight: '500',
    },
    threadAction: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-end',
      marginTop: 10,
      marginRight: 4,
    },
    reactionContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      paddingHorizontal: 8,
      marginTop: 4,
    },
    reactionBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.reactionBackground,
      borderRadius: 12,
      paddingHorizontal: 6,
      paddingVertical: 2,
      marginRight: 4,
      marginBottom: 4,
      borderWidth: 1,
      borderColor: colors.transparent,
    },
    reactionBadgeActive: {
      backgroundColor: colors.lightBlue,
      borderColor: colors.primary,
    },
    reactionCount: { marginLeft: 4, color: colors.messageMeta },
    reactionTextActive: { color: colors.primary, fontWeight: 'bold' },
    slackThreadContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 8,
      marginTop: 6,
      paddingVertical: 4,
    },
    participantStack: {
      flexDirection: 'row',
      alignItems: 'center',
      marginRight: 8,
    },
    threadAvatar: {
      width: 20,
      height: 20,
      borderRadius: 4,
      borderWidth: 1.5,
      borderColor: colors.white,
    },
    threadText: { color: colors.primary, marginLeft: 4 },
    threadCountExtra: { color: colors.messageMeta, marginLeft: 4 },
  });
}

export function createThreadMarkdownStyles(colors: ThemeColors) {
  return {
    text: { color: colors.textPrimary, fontSize: 15, flexShrink: 1 },
    paragraph: { marginVertical: 0, flexShrink: 1 },
    strong: { fontWeight: 'bold' as const, color: colors.textPrimary },
    em: { fontStyle: 'italic' as const, color: colors.textPrimary },
  };
}

export function createChatMenuOptionsStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: { padding: 20 },
    card: {
      backgroundColor: colors.reactionBackground,
      borderRadius: 16,
      overflow: 'hidden',
    },
    menuItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 18,
    },
    menuText: {
      fontSize: 16,
      color: colors.textPrimary,
      fontWeight: '500',
    },
    divider: {
      height: 1,
      backgroundColor: colors.border,
      marginHorizontal: 18,
    },
    statusText: {
      fontSize: 13,
      color: colors.messageMeta,
      marginLeft: 6,
    },
  });
}

export function createChatPopoverStyles(colors: ThemeColors) {
  return StyleSheet.create({
    wrapper: { ...StyleSheet.absoluteFillObject },
    overlay: { ...StyleSheet.absoluteFillObject },
    fab: {
      position: 'absolute',
      right: normalize(20),
      bottom: normalize(20),
      width: normalize(56),
      height: normalize(56),
      borderRadius: normalize(28),
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 5,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      zIndex: 100,
    },
    fabActive: { backgroundColor: colors.secondary },
    plusIcon: { width: 24, height: 24, tintColor: colors.white },
    popoverCard: {
      position: 'absolute',
      right: normalize(20),
      bottom: normalize(80),
      backgroundColor: colors.surface,
      borderRadius: normalize(12),
      width: normalize(210),
      paddingVertical: normalize(4),
      zIndex: 101,
      ...Platform.select({
        ios: {
          shadowColor: colors.black,
          shadowOffset: { width: 0, height: 12 },
          shadowOpacity: 0.15,
          shadowRadius: 16,
        },
        android: { elevation: 12 },
      }),
    },
    menuItem: {
      flexDirection: 'row',
      alignItems: 'center',
      padding: normalize(16),
    },
    menuIcon: {
      width: 22,
      height: 22,
      marginRight: 12,
      tintColor: colors.iconDefault,
    },
    menuText: { color: colors.textPrimary },
    separator: {
      height: 1,
      backgroundColor: colors.categoryChip,
      marginHorizontal: normalize(16),
    },
  });
}

export function createForwardedBlockStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flexDirection: 'row',
      marginTop: 8,
      marginBottom: 2,
    },
    accentLine: {
      width: 4,
      borderRadius: 4,
      backgroundColor: colors.border,
      marginRight: 10,
    },
    content: {
      flex: 1,
      minWidth: 0,
    },
    authorRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 4,
    },
    avatar: {
      width: 20,
      height: 20,
      borderRadius: 4,
      marginRight: 8,
    },
    avatarPlaceholder: {
      backgroundColor: colors.reactionBackground,
      alignItems: 'center',
      justifyContent: 'center',
    },
    senderName: {
      color: colors.textPrimary,
      flexShrink: 1,
    },
    messageText: {
      color: colors.textPrimary,
      fontSize: 15,
      lineHeight: 22,
    },
    mentionText: {
      color: colors.primary,
      backgroundColor: colors.lightBlue,
    },
    channelMentionText: {
      color: colors.channelMentionForeground,
      backgroundColor: colors.channelMentionBackground,
    },
    linkText: {
      color: colors.primary,
      textDecorationLine: 'underline',
    },
    previewImage: {
      width: '100%',
      height: 160,
      borderRadius: 8,
      marginTop: 8,
      backgroundColor: colors.surfaceElevated,
    },
    fileRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 8,
      gap: 8,
    },
    fileIcon: {
      width: 34,
      height: 34,
      borderRadius: 6,
      backgroundColor: colors.messageMeta,
      alignItems: 'center',
      justifyContent: 'center',
    },
    fileIconText: { color: colors.white },
    fileName: {
      flex: 1,
      color: colors.textPrimary,
    },
    footerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      marginTop: 8,
    },
    footerText: { color: colors.textSecondary },
    footerIcon: { marginRight: 4 },
    footerChannel: {
      color: colors.textSecondary,
      maxWidth: '55%',
    },
  });
}

export function createChatMediaStyles(colors: ThemeColors) {
  return StyleSheet.create({
    sheetBackground: {
      backgroundColor: colors.surface,
      borderRadius: 20,
    },
    container: { flex: 1 },
    darkText: { color: colors.textPrimary },
    blueText: { color: colors.primary },
    statsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 15,
    },
    statsTextGroup: { flexDirection: 'row', alignItems: 'center' },
    viewLibraryBtn: { paddingHorizontal: 15 },
    galleryWrapper: {
      paddingVertical: 10,
      borderBottomWidth: 0.9,
      borderColor: colors.border,
    },
    galleryPadding: { paddingHorizontal: 20 },
    cameraBox: {
      width: 80,
      height: 80,
      borderRadius: 12,
      backgroundColor: colors.reactionBackground,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 10,
    },
    cameraIcon: { width: 30, height: 30, tintColor: colors.messageMeta },
    galleryItem: {
      width: 80,
      height: 80,
      marginRight: 10,
    },
    galleryImage: {
      width: 80,
      height: 80,
      borderRadius: 12,
      backgroundColor: colors.border,
      borderWidth: 0.5,
      borderColor: colors.border,
    },
    videoBadge: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: 'center',
      alignItems: 'center',
    },
    videoBadgeCircle: {
      width: 24,
      height: 24,
      borderRadius: 12,
      backgroundColor: 'rgba(0, 0, 0, 0.55)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    videoBadgeIcon: { marginLeft: 2 },
    menuScroll: { paddingHorizontal: 20, paddingTop: 10, paddingBottom: 20 },
    menuItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.reactionBackground,
    },
    menuIconContainer: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.reactionBackground,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 15,
    },
    menuIcon: { width: 20, height: 20, tintColor: colors.iconDefault },
    menuLabel: { color: colors.textPrimary },
    selectionOverlay: {
      ...StyleSheet.absoluteFillObject,
      borderRadius: 12,
      justifyContent: 'flex-end',
      alignItems: 'flex-end',
      paddingRight: 6,
      paddingBottom: 6,
    },
    checkmarkCircle: {
      width: 20,
      height: 20,
      borderRadius: 14,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    selectionBadge: {
      marginLeft: 8,
      paddingHorizontal: 8,
      paddingVertical: 4,
      backgroundColor: colors.primary,
      borderRadius: 12,
    },
    badgeText: { color: colors.white, fontWeight: '600' },
    confirmButtonContainer: {
      paddingHorizontal: 20,
      paddingVertical: 12,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      backgroundColor: colors.surface,
    },
    confirmButton: {
      paddingVertical: 14,
      paddingHorizontal: 20,
      backgroundColor: colors.primary,
      borderRadius: 12,
      alignItems: 'center',
    },
    confirmButtonText: { color: colors.white, fontSize: 16 },
    viewerContainer: { flex: 1, backgroundColor: colors.black },
    headerIcon: {
      width: 20,
      height: 20,
      objectFit: 'contain',
      tintColor: colors.white,
    },
    headerContent: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.black,
      justifyContent: 'space-between',
      paddingHorizontal: 15,
      height: 100,
      paddingTop: Platform.OS === 'ios' ? 40 : 20,
      zIndex: 100,
    },
    backBtn: { flexDirection: 'row', alignItems: 'center' },
    userInfo: { marginLeft: 15 },
    content: { flex: 1 },
    mediaWrapper: {
      flex: 1,
      width: width,
      backgroundColor: colors.black,
      justifyContent: 'center',
      alignItems: 'center',
    },
    fullMedia: { width: width, height: height },
    fullVideo: { width: width, height: height },
    hiddenVideo: { opacity: 0 },
    touchOverlay: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 5,
    },
    playBtnCircleLarge: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.white,
      justifyContent: 'center',
      alignItems: 'center',
      paddingLeft: 4,
    },
    videoControls: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      position: 'absolute',
      bottom: Platform.OS === 'ios' ? 40 : 20,
      width: '100%',
      zIndex: 20,
      backgroundColor: colors.black,
      paddingVertical: 10,
    },
    timeLabel: { color: colors.white, width: 45, textAlign: 'center' },
    progressBar: {
      flex: 1,
      height: 24,
      justifyContent: 'center',
      marginHorizontal: 10,
    },
    speedBadge: {
      backgroundColor: colors.textMuted,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.white,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 10,
      paddingVertical: 12,
      backgroundColor: colors.surface,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
      elevation: 2,
    },
    iconBtn: {
      width: 32,
      height: 32,
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerTitle: {
      flex: 1,
      textAlign: 'center',
      fontSize: 18,
      color: colors.textPrimary,
    },
    customTabBarContainer: {
      backgroundColor: colors.surface,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
      elevation: 1,
    },
    customTabBar: {
      position: 'relative',
      height: 48,
      backgroundColor: colors.surface,
    },
    customTabScrollContent: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 48,
      paddingHorizontal: 8,
    },
    customTabBtn: {
      justifyContent: 'center',
      alignItems: 'center',
      height: 48,
      paddingHorizontal: 16,
    },
    customTabLabel: {
      color: colors.messageMeta,
      fontWeight: 'bold',
      fontSize: 15,
      letterSpacing: 0.2,
    },
    customTabLabelActive: {
      color: colors.primary,
    },
    customTabUnderline: {
      position: 'absolute',
      bottom: 0,
      height: 3,
      backgroundColor: colors.primary,
      borderRadius: 2,
    },
    tabContentContainer: {
      flex: 1,
      backgroundColor: colors.surface,
    },
    loadingWrap: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingVertical: 40,
    },
    mediaGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      padding: 8,
      justifyContent: 'flex-start',
    },
    mediaItem: {
      width: width / 3 - 14,
      height: width / 3 - 14,
      margin: 4,
      borderRadius: 10,
      overflow: 'hidden',
      backgroundColor: colors.reactionBackground,
      position: 'relative',
      borderWidth: 1,
      borderColor: colors.border,
    },
    mediaImage: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
    videoPlaceholder: {
      flex: 1,
      backgroundColor: colors.black,
      justifyContent: 'center',
      alignItems: 'center',
    },
    audioPlaceholder: {
      flex: 1,
      backgroundColor: colors.channelAvatarBackground,
      justifyContent: 'center',
      alignItems: 'center',
    },
    docGridPlaceholder: {
      flex: 1,
      backgroundColor: colors.surfaceElevated,
      justifyContent: 'center',
      alignItems: 'center',
    },
    linksList: {
      padding: 12,
    },
    linkItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
    },
    linkText: {
      color: colors.primary,
      fontSize: 15,
      flex: 1,
    },
    docItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
    },
    docText: {
      color: colors.textPrimary,
      fontSize: 15,
      flex: 1,
    },
    emptyText: {
      color: colors.messageMeta,
      textAlign: 'center',
      marginTop: 40,
      fontSize: 15,
    },
    footerLoader: {
      width: '100%',
      paddingVertical: 16,
      alignItems: 'center',
    },
  });
}

export function createMediaEditorStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.black },
    safeArea: { flex: 1 },
    header: {
      height: 60,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 15,
      marginTop: Platform.OS === 'ios' ? normalize(40) : 0,
    },
    closeBtn: {
      width: 40,
      height: 40,
      zIndex: 40,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.topNavigation,
      justifyContent: 'center',
      alignItems: 'center',
    },
    headerIcon: {
      width: 20,
      height: 20,
      tintColor: colors.textPrimary,
    },
    previewArea: {
      flex: 1,
      backgroundColor: colors.black,
      overflow: 'hidden',
      justifyContent: 'center',
      alignItems: 'center',
    },
    uploadProgressBar: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: 3,
      backgroundColor: colors.channelAvatarBackground,
      zIndex: 100,
    },
    uploadProgressFill: {
      height: '100%',
      width: '40%',
      backgroundColor: colors.primary,
    },
    videoContainer: {
      width: '90%',
      height: 320,
      alignSelf: 'center',
      borderRadius: 18,
      backgroundColor: colors.black,
      overflow: 'hidden',
      marginVertical: 16,
      justifyContent: 'center',
      alignItems: 'center',
    },
    mainPreview: { width: '100%', height: '100%', borderRadius: 18 },
    touchOverlay: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 10,
    },
    playIconCircle: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.white,
      justifyContent: 'center',
      alignItems: 'center',
      paddingLeft: 2,
      shadowColor: colors.black,
      shadowOpacity: 0.15,
      shadowRadius: 8,
    },
    filePreviewContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
      backgroundColor: colors.black,
      borderRadius: 18,
      width: '88%',
      alignSelf: 'center',
      marginVertical: 16,
    },
    officePreviewWrap: { width: '100%' },
    officePreviewMeta: { marginTop: 16, alignItems: 'center' },
    officeBadge: {
      borderRadius: 6,
      paddingHorizontal: 8,
      paddingVertical: 3,
      marginBottom: 10,
    },
    officeBadgeText: { color: colors.white, fontSize: 11 },
    fileNameText: {
      fontSize: 18,
      fontWeight: '600',
      color: colors.white,
      textAlign: 'center',
      marginTop: 15,
    },
    fileSizeText: { fontSize: 14, color: colors.textSecondary, marginTop: 5 },
    bottomBar: {
      padding: 15,
      backgroundColor: colors.black,
      borderTopLeftRadius: 18,
      borderTopRightRadius: 18,
    },
    inputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.black,
      borderRadius: 25,
      paddingHorizontal: 10,
      paddingVertical: Platform.OS === 'ios' ? 10 : 5,
      minHeight: 50,
      maxHeight: 120,
      marginBottom: 15,
      borderWidth: 1,
      borderColor: colors.border,
    },
    input: {
      flex: 1,
      color: colors.white,
      fontSize: 16,
      paddingLeft: 10,
      textAlignVertical: 'center',
    },
    mediaIconBtn: { padding: 5 },
    miniThumb: {
      width: 20,
      height: 20,
      borderRadius: 20,
      backgroundColor: colors.white,
      padding: 2,
    },
    footerActions: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    onceViewBtn: {
      paddingHorizontal: 15,
      paddingVertical: 8,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: colors.primary,
      backgroundColor: colors.black,
    },
    onceText: { fontSize: 14, color: colors.white },
    sendBtn: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    sendIcon: { width: 24, height: 24, tintColor: colors.white, marginLeft: 4 },
    scrubberContainer: {
      position: 'absolute',
      bottom: 10,
      width: '100%',
      paddingHorizontal: 10,
      zIndex: 20,
    },
    sliderThumb: {
      width: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: colors.primary,
      borderWidth: 2,
      borderColor: colors.white,
      shadowColor: colors.black,
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    videoInfoOverlay: {
      position: 'absolute',
      top: 20,
      alignSelf: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.54)',
      paddingHorizontal: 12,
      paddingVertical: 4,
      borderRadius: 20,
      zIndex: 25,
    },
    videoInfoText: {
      color: colors.white,
      fontSize: 13,
      fontWeight: '600',
    },
    imagePreviewWrapper: {
      width: '90%',
      height: normalize(450),
      backgroundColor: colors.black,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
      marginVertical: 16,
      overflow: 'hidden',
    },
    imagePreview: {
      width: '100%',
      height: '100%',
      borderRadius: 18,
    },
    multipleImagesContainer: {
      width: '100%',
      height: normalize(450),
      backgroundColor: colors.black,
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
      marginVertical: 16,
      overflow: 'hidden',
    },
    imagesScrollContent: { height: normalize(450) },
    imagePage: {
      width: normalize(300),
      height: normalize(450),
      justifyContent: 'center',
      alignItems: 'center',
      marginHorizontal: 15,
    },
    imageCountText: {
      color: colors.textSecondary,
      fontSize: 12,
      marginTop: 8,
    },
  });
}

export function createMentionItemStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      paddingHorizontal: normalize(16),
      paddingVertical: normalize(12),
      backgroundColor: colors.white,
      borderBottomWidth: 1,
      borderBottomColor: colors.reactionBackground,
    },
    avatarContainer: {
      marginRight: normalize(12),
      marginTop: normalize(4),
    },
    avatar: {
      width: normalize(40),
      height: normalize(40),
      borderRadius: normalize(24),
      backgroundColor: colors.primary,
    },
    avatarPlaceholder: {
      justifyContent: 'center',
      alignItems: 'center',
    },
    contentContainer: { flex: 1 },
    headerRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      marginBottom: normalize(6),
    },
    nameContainer: {
      flex: 1,
      marginRight: normalize(8),
    },
    username: { color: colors.textPrimary },
    channelName: {
      color: colors.messageMeta,
      marginTop: normalize(2),
    },
    time: { color: colors.messageMeta },
    message: {
      color: colors.iconDefault,
      lineHeight: 18,
    },
    threadBadge: {
      alignSelf: 'flex-start',
      backgroundColor: colors.reactionBackground,
      paddingHorizontal: normalize(8),
      paddingVertical: normalize(4),
      borderRadius: normalize(4),
      marginTop: normalize(6),
    },
    threadText: { color: colors.messageMeta },
    chevron: {
      width: normalize(16),
      height: normalize(16),
      tintColor: colors.iconDefault,
      transform: [{ rotate: '180deg' }],
      marginLeft: normalize(8),
      marginTop: normalize(8),
      objectFit: 'contain',
    },
    channelContainer: {
      width: '100%',
      backgroundColor: colors.surfaceElevated,
      paddingVertical: normalize(6),
      paddingHorizontal: normalize(12),
      borderTopLeftRadius: normalize(6),
      borderTopRightRadius: normalize(6),
      marginBottom: normalize(8),
    },
    channelInner: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    channelText: {
      color: colors.iconDefault,
      marginLeft: normalize(6),
    },
  });
}

export function createToastStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      width: width * 0.94,
      zIndex: 9999,
    },
    innerContent: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderWidth: 1,
      borderColor: colors.border,
      ...Platform.select({
        ios: {
          shadowColor: colors.black,
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.15,
          shadowRadius: 10,
        },
        android: { elevation: 8 },
      }),
    },
    content: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    avatarWrapper: { position: 'relative' },
    avatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.reactionBackground,
      objectFit: 'contain',
    },
    onlineIndicator: {
      position: 'absolute',
      bottom: 2,
      right: 2,
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: colors.online,
      borderWidth: 2,
      borderColor: colors.white,
    },
    textContainer: {
      flex: 1,
      marginLeft: 12,
      justifyContent: 'center',
    },
    title: {
      color: colors.textPrimary,
      marginBottom: 2,
    },
    message: {
      color: colors.iconDefault,
      lineHeight: 18,
    },
    rightAction: { paddingLeft: 8 },
    timeDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.primary,
    },
    grabber: {
      width: 35,
      height: 4,
      backgroundColor: colors.border,
      borderRadius: 2,
      alignSelf: 'center',
      marginTop: 8,
    },
  });
}

export function createLogoutModalStyles(colors: ThemeColors) {
  return StyleSheet.create({
    overlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: normalize(30),
    },
    modalContainer: {
      width: '100%',
      backgroundColor: colors.surface,
      borderRadius: normalize(20),
      padding: normalize(24),
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    title: {
      fontSize: normalize(20),
      color: colors.textPrimary,
      marginBottom: normalize(12),
    },
    message: {
      fontSize: normalize(15),
      color: colors.textSecondary,
      textAlign: 'center',
      lineHeight: normalize(22),
      marginBottom: normalize(24),
    },
    buttonContainer: {
      flexDirection: 'row',
      width: '100%',
      justifyContent: 'space-between',
    },
    cancelButton: {
      flex: 1,
      height: normalize(48),
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: normalize(12),
      borderRadius: normalize(12),
      backgroundColor: colors.reactionBackground,
    },
    cancelText: {
      color: colors.textPrimary,
      fontSize: normalize(16),
    },
    logoutButton: {
      flex: 1,
      height: normalize(48),
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: normalize(12),
      backgroundColor: colors.error,
      flexDirection: 'row',
      gap: 6,
    },
    logoutText: {
      color: colors.white,
      fontSize: normalize(16),
    },
  });
}

export function createStatusSheetStyles(colors: ThemeColors) {
  return StyleSheet.create({
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    iconBtn: { padding: 4 },
    saveBtn: { paddingVertical: 4, paddingHorizontal: 8 },
    title: { fontSize: 18, color: colors.textPrimary },
    content: { paddingHorizontal: 0 },
    inputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginHorizontal: 16,
      marginVertical: 16,
      borderWidth: 1,
      borderColor: colors.textSecondary,
      borderRadius: 8,
      paddingHorizontal: 8,
      paddingVertical: Platform.OS === 'ios' ? 10 : 2,
    },
    emojiBtn: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 4,
    },
    textInput: {
      flex: 1,
      fontSize: 16,
      color: colors.textPrimary,
      fontFamily: Platform.OS === 'ios' ? 'System' : 'sans-serif',
    },
    clearInputBtn: { padding: 4 },
    clearAfterRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 16,
      paddingHorizontal: 16,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    rowLead: { flexDirection: 'row', alignItems: 'center' },
    rowLabel: { marginLeft: 12, fontSize: 16, color: colors.textPrimary },
    rowTail: { flexDirection: 'row', alignItems: 'center' },
    rowSub: { color: colors.textSecondary, marginRight: 4, fontSize: 15 },
    sectionHeader: {
      backgroundColor: colors.surfaceElevated,
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    sectionHeaderText: {
      fontSize: 12,
      color: colors.textSecondary,
      letterSpacing: 0.5,
    },
    presetRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    presetLead: { flexDirection: 'row', alignItems: 'center' },
    presetEmojiWrap: { width: 32, alignItems: 'center' },
    presetLabel: { fontSize: 16, color: colors.textPrimary, marginLeft: 8 },
    presetNote: { color: colors.textSecondary, fontSize: 14 },
    clearSelectionRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 16,
      paddingHorizontal: 20,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    clearOptionText: { fontSize: 16, color: colors.textPrimary },
  });
}

export function createAddDescriptionStyles(colors: ThemeColors) {
  return StyleSheet.create({
    mainWrapper: {
      flex: 1,
      backgroundColor: colors.surface,
    },
    navHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 15,
      backgroundColor: colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: colors.reactionBackground,
    },
    navTitleCenter: { alignItems: 'center' },
    navTitle: { fontSize: 17, fontWeight: '700', color: colors.textPrimary },
    navActionText: { fontSize: 16, color: colors.primary },
    searchSection: { paddingHorizontal: 20, marginTop: 30 },
  });
}

export function createExitChatStyles(colors: ThemeColors) {
  return StyleSheet.create({
    mainWrapper: {
      flex: 1,
      backgroundColor: colors.surface,
      paddingBottom: 40,
    },
    header: {
      alignItems: 'center',
      paddingTop: 10,
      paddingBottom: 20,
    },
    iconContainer: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: colors.surfaceElevated,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 12,
    },
    headerTitle: { color: colors.textPrimary },
    content: { paddingHorizontal: 24 },
    warningBox: {
      backgroundColor: colors.surfaceElevated,
      padding: 16,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
    },
    warningText: {
      fontSize: 15,
      color: colors.messageMeta,
      lineHeight: 22,
      textAlign: 'center',
    },
    footer: {
      flexDirection: 'row',
      marginTop: 30,
      gap: 12,
    },
    cancelButton: {
      flex: 1,
      height: 52,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.reactionBackground,
    },
    exitButton: {
      flex: 1,
      height: 52,
      borderRadius: 12,
      flexDirection: 'row',
      gap: 5,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.error,
      shadowColor: colors.error,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 3,
    },
    cancelBtnText: {
      color: colors.textSecondary,
      fontSize: 16,
    },
    exitBtnText: {
      color: colors.white,
      fontSize: 16,
    },
  });
}

export function createNotificationPrefModalStyles(colors: ThemeColors) {
  return StyleSheet.create({
    headerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      paddingVertical: 15,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    container: {
      padding: 24,
      paddingBottom: 100,
    },
    title: {
      fontSize: 22,
      color: colors.textPrimary,
    },
    sectionLabel: {
      fontSize: 16,
      color: colors.textPrimary,
      marginBottom: 16,
      fontWeight: '600',
    },
    optionsGroup: { marginBottom: 20 },
    radioRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
    },
    radioLabel: {
      fontSize: 16,
      color: colors.textPrimary,
      marginLeft: 10,
    },
    checkboxGroup: {
      marginTop: 10,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingTop: 20,
    },
    checkboxRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 18,
    },
    checkboxLabel: {
      fontSize: 16,
      color: colors.textPrimary,
      marginLeft: 10,
      flex: 1,
    },
    note: {
      color: colors.textSecondary,
      fontSize: 14,
      marginTop: 10,
      lineHeight: 20,
    },
    link: {
      color: colors.primary,
      textDecorationLine: 'underline',
    },
    buttonRow: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      alignItems: 'center',
      marginTop: 32,
      gap: 12,
    },
    cancelButton: {
      paddingVertical: 12,
      paddingHorizontal: 16,
    },
    cancelText: {
      color: colors.textSecondary,
      fontSize: 16,
      fontWeight: '600',
    },
    saveButton: {
      paddingVertical: 12,
      paddingHorizontal: 24,
      borderRadius: 8,
      backgroundColor: colors.secondary,
      minWidth: 140,
      alignItems: 'center',
    },
    saveText: {
      color: colors.white,
      fontWeight: '600',
      fontSize: 16,
    },
  });
}

export function createDocumentViewerStyles(colors: ThemeColors) {
  return StyleSheet.create({
    modalRoot: {
      flex: 1,
      backgroundColor: colors.background,
      paddingTop: Platform.OS === 'ios' ? 52 : 24,
    },
    viewerContainer: {
      flex: 1,
      backgroundColor: colors.background,
    },
    chrome: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingBottom: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.surface,
    },
    iconButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surfaceElevated,
    },
    iconButtonPlaceholder: {
      width: 40,
      height: 40,
    },
    chromeTitleWrap: {
      flex: 1,
      paddingHorizontal: 10,
    },
    chromeMeta: {
      color: colors.messageMeta,
      marginTop: 2,
    },
    webviewWrap: {
      flex: 1,
      backgroundColor: colors.surfaceElevated,
    },
    webview: {
      flex: 1,
      backgroundColor: colors.background,
    },
    loadingOverlay: {
      ...StyleSheet.absoluteFillObject,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.background,
      zIndex: 2,
    },
    loadingText: {
      color: colors.messageMeta,
      marginTop: 12,
    },
    fallbackState: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 28,
    },
    fallbackIcon: {
      width: 72,
      height: 72,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
    },
    fallbackIconText: {
      color: colors.white,
      fontSize: 18,
    },
    fallbackTitle: {
      color: colors.textPrimary,
      textAlign: 'center',
      marginTop: 16,
    },
    fallbackSubtitle: {
      color: colors.messageMeta,
      textAlign: 'center',
      marginTop: 8,
      lineHeight: 20,
    },
    fallbackButton: {
      marginTop: 20,
      backgroundColor: colors.primary,
      borderRadius: 12,
      minWidth: 200,
      minHeight: 46,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 18,
    },
    fallbackButtonText: {
      color: colors.white,
    },
  });
}
