import { Platform, StyleSheet } from 'react-native';
import type { ThemeColors } from './types';

export function createSettingsStyles(colors: ThemeColors) {
  return StyleSheet.create({
    header: {
      backgroundColor: colors.secondary,
      paddingHorizontal: 10,
      paddingVertical: Platform.OS === 'ios' ? 30 : 20,
    },
    profileCard: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: 'rgba(255,255,255,0.1)',
      padding: 12,
      borderRadius: 16,
    },
    profileInfo: { flexDirection: 'row', alignItems: 'center' },
    avatarWrapper: { position: 'relative' },
    avatar: { width: 50, height: 50, borderRadius: 25 },
    activeBadge: {
      position: 'absolute',
      bottom: 2,
      right: 2,
      width: 12,
      height: 12,
      borderRadius: 6,
      borderWidth: 2,
      borderColor: colors.secondary,
    },
    nameSection: { marginLeft: 12, rowGap: 3 },
    userName: { color: colors.white, fontSize: 18 },
    userStatus: { color: 'rgba(255,255,255,0.7)', fontSize: 13 },
    edit: {
      backgroundColor: colors.secondary,
      alignItems: 'center',
      justifyContent: 'center',
      height: 35,
      width: 35,
      borderRadius: 50,
    },
    editLink: { color: colors.white, fontSize: 15 },
    scrollBody: { flex: 1 },
    innerContent: { paddingHorizontal: 16, paddingVertical: 5 },
    sectionHeader: {
      fontSize: 13,
      color: colors.textSecondary,
      marginBottom: 8,
      marginTop: 16,
      textTransform: 'uppercase',
    },
    groupCard: {
      backgroundColor: colors.surface,
      borderRadius: 12,
      overflow: 'hidden',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
    },
    itemRow: { flexDirection: 'row', alignItems: 'center', padding: 14 },
    iconContainer: { width: 32, alignItems: 'center' },
    textContainer: { flex: 1, marginLeft: 12 },
    itemTitle: { fontSize: 16, color: colors.textPrimary },
    itemSubtitle: { fontSize: 13, color: colors.textSecondary, marginTop: 2 },
    divider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.border,
      marginLeft: 58,
    },
    statusRow: {
      paddingVertical: 15,
      paddingHorizontal: 16,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
    },
    statusInner: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    statusEmojiContainer: {
      width: 28,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statusTextContainer: {
      flex: 1,
      marginLeft: 12,
    },
    statusText: {
      fontSize: 16,
      color: colors.textPrimary,
    },
    placeholderText: {
      color: colors.iconMuted,
    },
  });
}

export function createWorkspaceDrawerStyles(
  colors: ThemeColors,
  drawerWidth: number,
) {
  return StyleSheet.create({
    drawerContainer: {
      width: drawerWidth,
      height: '100%',
      backgroundColor: colors.surface,
      paddingTop: Platform.OS === 'ios' ? 0 : 20,
    },
    header: {
      paddingHorizontal: 20,
      paddingVertical: 15,
      backgroundColor: colors.surface,
    },
    scrollContent: {
      paddingBottom: 10,
    },
    workspaceItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 12,
    },
    activeWorkspaceItem: {
      backgroundColor: colors.surfaceElevated,
    },
    activeIndicator: {
      position: 'absolute',
      left: 0,
      width: 4,
      height: '100%',
      backgroundColor: colors.primary,
      borderTopRightRadius: 4,
      borderBottomRightRadius: 4,
    },
    logoContainer: {
      width: 48,
      height: 48,
      borderRadius: 8,
      backgroundColor: colors.surfaceElevated,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 15,
    },
    logo: { width: 48, height: 48, borderRadius: 8 },
    placeholderLogo: {
      width: 48,
      height: 48,
      borderRadius: 8,
      backgroundColor: colors.categoryChip,
      justifyContent: 'center',
      alignItems: 'center',
    },
    placeholderText: { fontSize: 17, color: colors.textPrimary },
    workspaceInfo: { flex: 1 },
    staticFooter: {
      backgroundColor: colors.surface,
      paddingBottom: Platform.OS === 'ios' ? 10 : 20,
    },
    divider: {
      height: 1,
      backgroundColor: colors.border,
      marginVertical: 10,
    },
    actionItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 15,
    },
    actionIcon: { marginRight: 15, width: 25 },
  });
}

export function createChatDetailStyles(colors: ThemeColors) {
  return StyleSheet.create({
    header: {
      height: 60,
      backgroundColor: colors.topNavigation,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 10,
      gap: 5,
      zIndex: 10,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
    },
    backBtn: {
      alignItems: 'center',
      height: 40,
      width: 40,
      paddingHorizontal: 5,
      justifyContent: 'center',
    },
    headerIcon: {
      width: 20,
      height: 20,
      resizeMode: 'contain',
      tintColor: colors.iconDefault,
    },
    avatarStack: { flexDirection: 'row', alignItems: 'center' },
    avatarBadge: {
      position: 'absolute',
      bottom: -2,
      right: -5,
      backgroundColor: colors.textMuted,
      width: 22,
      height: 22,
      borderRadius: 11,
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 10,
      borderWidth: 2,
      borderColor: colors.surface,
    },
    stackItem: {
      width: 35,
      height: 35,
      borderRadius: 25,
      borderWidth: 2,
      borderColor: colors.topNavigation,
    },
    stackOver: { marginLeft: -15, zIndex: 12 },
    countBadge: {
      width: 18,
      height: 18,
      borderRadius: 11,
      backgroundColor: colors.textMuted,
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: -10,
      borderWidth: 1.5,
      borderColor: colors.topNavigation,
      zIndex: 9,
      marginTop: 10,
    },
    countText: { color: colors.white, fontSize: 10, fontWeight: 'bold' },
    headerInfo: { flex: 1 },
    moreBtn: { padding: 5 },
    headerAvatarContainer: { marginLeft: 5 },
    headerAvatar: { width: 36, height: 36, borderRadius: 18 },
    headerIconMore: {
      height: 20,
      objectFit: 'contain',
      tintColor: colors.iconDefault,
    },
    listContent: { padding: 5, paddingBottom: 20 },
    emojiWrapper: { height: 300, backgroundColor: colors.surface },
    videoIconWrap: {
      position: 'relative',
    },
    activeBuzzDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.online,
      position: 'absolute',
      top: -1,
      right: -2,
      borderWidth: 1,
      borderColor: colors.topNavigation,
    },
    joinFooter: {
      padding: 15,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      alignItems: 'center',
      gap: 10,
      flex: 1,
      flexGrow: 1,
      height: '100%',
      backgroundColor: colors.background,
    },
    joinPrompt: {
      paddingHorizontal: 15,
      paddingTop: 56,
    },
    joinText: {
      color: colors.textSecondary,
      textAlign: 'center',
      marginBottom: 25,
      fontSize: 13,
    },
    joinButton: {
      backgroundColor: colors.primary,
      width: '100%',
      height: 48,
      borderRadius: 8,
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
      gap: 5,
    },
    joinButtonText: {
      color: colors.white,
      fontSize: 16,
    },
  });
}

/** Shared styles for settings stack sub-screens (notifications, security, etc.). */
export function createSettingsSubScreenStyles(colors: ThemeColors) {
  return StyleSheet.create({
    stackHeader: {
      height: 60,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      backgroundColor: colors.background,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    stackHeaderCompact: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      padding: 16,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
      backgroundColor: colors.background,
    },
    backBtn: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    backBtnCompact: { flexDirection: 'row', alignItems: 'center', gap: 5 },
    headerTitle: { fontSize: 18, color: colors.textPrimary },
    headerIcon: {
      width: 20,
      height: 20,
      objectFit: 'contain',
      tintColor: colors.iconDefault,
    },
    scrollContent: { paddingBottom: 60 },
    formContent: { paddingHorizontal: 20, paddingTop: 25 },
    introSection: { marginBottom: 25 },
    subText: { fontSize: 16, color: colors.textSecondary },
    sectionContainer: { marginBottom: 20 },
    sectionTitle: {
      fontSize: 16,
      color: colors.textPrimary,
      marginBottom: 15,
    },
    sectionTitleLarge: {
      fontSize: 18,
      marginBottom: 15,
      color: colors.textPrimary,
    },
    radioRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 18 },
    radioOuter: {
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 2,
      borderColor: colors.iconMuted,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    radioOuterActive: { borderColor: colors.primary },
    radioInner: {
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: colors.primary,
    },
    radioLabel: { fontSize: 16, color: colors.textPrimary },
    divider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.border,
      marginBottom: 25,
    },
    dividerInset: {
      height: 1,
      backgroundColor: colors.border,
      marginVertical: 12,
    },
    timePickerContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 15,
    },
    timeBox: { width: '47%' },
    labelSmall: {
      color: colors.textPrimary,
      marginBottom: 6,
      fontWeight: '600',
    },
    timeInput: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 10,
      paddingHorizontal: 12,
      height: 54,
      backgroundColor: colors.surfaceElevated,
    },
    timeValue: { fontSize: 16, color: colors.textPrimary, fontWeight: '400' },
    noteText: { fontSize: 14, color: colors.textSecondary },
    toggleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 20,
      gap: 15,
    },
    toggleContainer: {
      width: 44,
      height: 24,
      borderRadius: 12,
      padding: 2,
      justifyContent: 'center',
    },
    toggleCircle: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: colors.white,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 2,
      elevation: 2,
    },
    toggleLabel: { fontSize: 16, color: colors.textPrimary, flex: 1 },
    saveButton: {
      backgroundColor: colors.primary,
      height: 56,
      borderRadius: 14,
      flexDirection: 'row',
      gap: 3,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 20,
    },
    saveButtonCompact: {
      backgroundColor: colors.primary,
      height: 48,
      paddingHorizontal: 24,
      borderRadius: 8,
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
    },
    saveButtonText: { color: colors.white, fontSize: 16 },
    disabledButton: { backgroundColor: colors.iconMuted },
    timeOption: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 15,
      paddingHorizontal: 20,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    timeOptionText: { fontSize: 16, color: colors.textPrimary },
    timeOptionTextActive: { color: colors.primary, fontWeight: 'bold' },
    skeleton: {
      backgroundColor: colors.skeleton,
      borderRadius: 8,
    },
    groupCard: {
      backgroundColor: colors.surface,
      borderRadius: 14,
      padding: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      marginBottom: 16,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 10,
      elevation: 2,
    },
    emptyText: { color: colors.textSecondary, marginTop: 10 },
    bottomActions: {
      paddingHorizontal: 20,
      paddingBottom: Platform.OS === 'ios' ? 30 : 20,
      paddingTop: 10,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
      backgroundColor: colors.background,
    },
  });
}

export function createProfileScreenStyles(colors: ThemeColors) {
  const sub = createSettingsSubScreenStyles(colors);
  return StyleSheet.create({
    ...sub,
    header: {
      height: 56,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
      backgroundColor: colors.background,
    },
    scrollContent: { paddingHorizontal: 20, paddingBottom: 40 },
    photoSection: { alignItems: 'center', marginTop: 30 },
    largeAvatar: {
      width: 120,
      height: 120,
      borderRadius: 60,
      backgroundColor: colors.surfaceElevated,
    },
    statusDot: {
      position: 'absolute',
      bottom: 5,
      right: 5,
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 3,
      borderColor: colors.surface,
    },
    editPhotoBtn: { marginTop: 12, paddingVertical: 8, paddingHorizontal: 16 },
    editPhotoText: { color: colors.primary, fontSize: 16 },
    awayToggle: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 16,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      marginTop: 20,
      marginBottom: 10,
    },
    awayLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
      minWidth: 0,
      marginRight: 8,
    },
    awayTextGroup: { marginLeft: 12, flex: 1, minWidth: 0 },
    awayText: { fontSize: 16, color: colors.textPrimary },
    awayDescription: {
      fontSize: 13,
      color: colors.messageMeta,
      marginTop: 2,
      lineHeight: 18,
    },
    awayToggleIcon: { flexShrink: 0 },
    formContainer: { marginTop: 10 },
    saveButton: {
      backgroundColor: colors.primary,
      height: 52,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 40,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 4,
      flexDirection: 'row',
      gap: 5,
    },
    leaveOrgButton: {
      height: 52,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 16,
      borderWidth: 1.5,
      borderColor: colors.error,
    },
    leaveOrgButtonText: { color: colors.error, fontSize: 16 },
    leaveSheetContent: {
      flex: 1,
      paddingHorizontal: 24,
      paddingBottom: 40,
    },
    leaveSheetHeader: {
      alignItems: 'center',
      paddingTop: 10,
      paddingBottom: 20,
    },
    leaveSheetIconContainer: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: colors.surfaceElevated,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 12,
    },
    leaveSheetTitle: { color: colors.textPrimary },
    leaveSheetQuestion: {
      fontSize: 15,
      color: colors.messageMeta,
      lineHeight: 22,
      textAlign: 'center',
    },
    leaveSheetOrgName: { color: colors.textMuted },
    leaveSheetSubtitle: {
      fontSize: 15,
      color: colors.textMuted,
      marginTop: 20,
      marginBottom: 12,
    },
    leaveSheetList: { gap: 10 },
    leaveSheetListItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    leaveSheetListText: {
      flex: 1,
      fontSize: 14,
      color: colors.messageMeta,
      lineHeight: 20,
    },
    leaveSheetActions: {
      flexDirection: 'row',
      marginTop: 30,
      gap: 12,
    },
    leaveSheetCancelButton: {
      flex: 1,
      height: 52,
      borderRadius: 12,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.surfaceElevated,
    },
    leaveSheetCancelText: { color: colors.textSecondary, fontSize: 16 },
    leaveSheetContinueButton: {
      flex: 1,
      height: 52,
      borderRadius: 12,
      flexDirection: 'row',
      gap: 5,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: colors.error,
    },
    leaveSheetContinueText: { color: colors.white, fontSize: 16 },
    sheetContent: {
      paddingHorizontal: 20,
      paddingTop: 10,
    },
    sheetOption: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 10,
    },
    iconCircle: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: colors.surfaceElevated,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 16,
    },
    optionText: {
      fontSize: 16,
      color: colors.textPrimary,
    },
  });
}

export function createSecurityScreenStyles(colors: ThemeColors) {
  const sub = createSettingsSubScreenStyles(colors);
  return StyleSheet.create({
    ...sub,
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      padding: 16,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
      backgroundColor: colors.background,
    },
    sessionCard: {
      backgroundColor: colors.surface,
      borderRadius: 14,
      padding: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      marginBottom: 16,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 10,
      elevation: 2,
    },
    scrollContent: { padding: 20 },
    sessionHeader: { flexDirection: 'row', alignItems: 'center' },
    iconContainer: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.surfaceElevated,
      justifyContent: 'center',
      alignItems: 'center',
    },
    sessionMeta: { flex: 1, marginLeft: 12 },
    deviceName: { fontSize: 15, color: colors.textPrimary },
    locationText: { fontSize: 13, color: colors.textSecondary, marginTop: 2 },
    statusBadge: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
    },
    activeBadge: { backgroundColor: colors.surfaceElevated },
    inactiveBadge: { backgroundColor: colors.categoryChip },
    statusText: { fontSize: 11, fontWeight: '700' },
    activeText: { color: colors.online },
    inactiveText: { color: colors.textSecondary },
    sessionDetails: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    detailItem: { flex: 1 },
    detailLabel: {
      fontSize: 11,
      color: colors.textSecondary,
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    detailValue: { fontSize: 13, color: colors.textPrimary, marginTop: 4 },
    emptyState: { alignItems: 'center', padding: 40 },
    loadMoreBtn: {
      paddingVertical: 12,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 16,
    },
    loadMoreText: {
      color: colors.primary,
      fontSize: 14,
      fontWeight: '600',
    },
  });
}

export function createAuthStyles(colors: ThemeColors) {
  return StyleSheet.create({
    scrollContent: {
      paddingHorizontal: 25,
      paddingBottom: 40,
      flexGrow: 1,
    },
    header: {
      alignItems: 'center',
      marginTop: 20,
      flexDirection: 'row',
      justifyContent: 'center',
    },
    logoContainer: {
      alignItems: 'center',
      marginTop: 40,
    },
    logo: {
      width: 100,
      height: 100,
      marginRight: 10,
    },
    logoForgot: {
      width: 100,
      height: 100,
      marginBottom: 10,
    },
    title: {
      textAlign: 'center',
      marginTop: 40,
      marginBottom: 30,
      color: colors.textPrimary,
    },
    titleCompact: {
      textAlign: 'center',
      marginTop: 10,
      marginBottom: 10,
      color: colors.textPrimary,
    },
    subtitle: {
      textAlign: 'center',
      color: colors.textSecondary,
      marginBottom: 30,
      fontSize: 16,
      paddingHorizontal: 10,
    },
    subtitleCode: {
      textAlign: 'center',
      color: colors.textSecondary,
      marginBottom: 40,
      lineHeight: 22,
    },
    socialBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      height: 52,
      borderWidth: 1.5,
      borderColor: colors.border,
      borderRadius: 10,
      marginBottom: 16,
    },
    socialIcon: { width: 22, height: 22, marginRight: 12 },
    dividerContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: 25,
    },
    line: { flex: 1, height: 1, backgroundColor: colors.border },
    orText: { marginHorizontal: 15, color: colors.textSecondary },
    forgotPasswordContainer: {
      alignSelf: 'flex-end',
      marginTop: -5,
      marginBottom: 25,
    },
    forgotPasswordText: { color: colors.primary, fontSize: 14 },
    submitBtn: { marginTop: 10, marginBottom: 16 },
    input: { marginBottom: 20 },
    footer: {
      flexDirection: 'row',
      justifyContent: 'center',
      marginTop: 30,
    },
    footerText: { color: colors.textMuted },
    linkText: { color: colors.primary },
    tabContainer: {
      flexDirection: 'row',
      backgroundColor: colors.surfaceElevated,
      padding: 4,
      borderRadius: 10,
      marginBottom: 30,
    },
    tab: {
      flex: 1,
      paddingVertical: 12,
      alignItems: 'center',
      borderRadius: 8,
    },
    activeTab: { backgroundColor: colors.surface },
    inputGap: { marginBottom: 20 },
    labelColor: { color: colors.textMuted, marginBottom: 8 },
    dropdown: {
      height: 52,
      borderColor: colors.border,
      borderWidth: 1.5,
      borderRadius: 8,
      paddingHorizontal: 15,
      backgroundColor: colors.surface,
    },
    dropdownContainer: {
      borderRadius: 8,
      marginTop: 5,
      elevation: 3,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      backgroundColor: colors.surface,
    },
    placeholderStyle: { fontSize: 16, color: colors.textSecondary },
    selectedTextStyle: { fontSize: 16, color: colors.textPrimary },
    inputSearchStyle: {
      height: 40,
      fontSize: 16,
      borderRadius: 8,
      color: colors.textPrimary,
    },
    chevron: { width: 16, height: 16 },
    codeRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 40,
    },
    codeBox: {
      width: 45,
      height: 55,
      borderWidth: 1.5,
      borderColor: colors.border,
      borderRadius: 10,
      backgroundColor: colors.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
    },
    codeBoxFocused: {
      borderColor: colors.primary,
      backgroundColor: colors.surface,
    },
    codeBoxFilled: { borderColor: colors.primary },
    codeInput: {
      textAlign: 'center',
      fontSize: 22,
      fontWeight: 'bold',
      width: '100%',
      height: '100%',
      color: colors.textPrimary,
    },
    disabledBtn: { opacity: 0.5 },
    resendContainer: { marginTop: 24, alignItems: 'center' },
    resendText: { color: colors.textSecondary, fontSize: 15 },
    resendActive: {
      color: colors.primary,
      fontWeight: 'bold',
      fontSize: 15,
      textDecorationLine: 'underline',
    },
    resendTime: { color: colors.primary, fontWeight: '700' },
  });
}

export function createInviteScreenStyles(colors: ThemeColors) {
  return StyleSheet.create({
    header: {
      height: 60,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
      backgroundColor: colors.background,
    },
    backBtn: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    headerTitle: { fontSize: 18, color: colors.textPrimary },
    sendBtn: { paddingHorizontal: 16, paddingVertical: 8 },
    sendBtnText: { color: colors.primary, fontSize: 16 },
    content: { padding: 20 },
    label: { color: colors.textPrimary, marginBottom: 10, fontSize: 14 },
    inputContainer: {
      minHeight: 80,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      padding: 12,
      backgroundColor: colors.surfaceElevated,
    },
    chipWrapper: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      alignItems: 'center',
    },
    chip: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surfaceElevated,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.primary,
      gap: 6,
    },
    chipText: { fontSize: 13, color: colors.textPrimary },
    input: {
      flex: 1,
      minWidth: 120,
      height: 40,
      fontSize: 15,
      color: colors.textPrimary,
    },
    hint: { marginTop: 8, fontSize: 12, color: colors.textSecondary },
    roleSection: { marginTop: 25 },
    rolesList: { gap: 10, paddingRight: 20 },
    roleChip: {
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    roleChipActive: {
      borderColor: colors.primary,
      backgroundColor: colors.surfaceElevated,
    },
    roleText: { fontSize: 14, color: colors.textSecondary },
    roleTextActive: { color: colors.primary, fontWeight: 'bold' },
    divider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.border,
      marginVertical: 30,
    },
    linkSection: { gap: 16 },
    linkHeader: { gap: 4 },
    sectionTitle: { fontSize: 16, color: colors.textPrimary },
    sectionSub: { fontSize: 13, color: colors.textSecondary },
    linkBox: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surfaceElevated,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 12,
      padding: 4,
      paddingLeft: 12,
    },
    linkContent: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    linkText: { color: colors.textSecondary, fontSize: 13, flex: 1 },
    copyBtn: {
      backgroundColor: colors.surface,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      minWidth: 80,
      alignItems: 'center',
    },
    copyBtnText: { color: colors.textPrimary, fontSize: 13 },
    shareOption: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginTop: 8,
    },
    shareIconCircle: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: colors.surfaceElevated,
      justifyContent: 'center',
      alignItems: 'center',
    },
    shareText: { color: colors.primary, fontSize: 15 },
  });
}

export function createBillingScreenStyles(colors: ThemeColors) {
  return StyleSheet.create({
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 16,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
      backgroundColor: colors.background,
    },
    headerTitle: { fontSize: 18, color: colors.textPrimary },
    scrollContent: { padding: 20 },
    row: { flexDirection: 'row', alignItems: 'center' },
    backBtn: { flexDirection: 'row', alignItems: 'center', gap: 4 },
    centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    skeleton: { backgroundColor: colors.skeleton, borderRadius: 8 },
    toggleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginVertical: 20,
    },
    toggleOuter: {
      width: 48,
      height: 24,
      borderRadius: 12,
      backgroundColor: colors.border,
      marginHorizontal: 12,
      padding: 2,
    },
    toggleThumb: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: colors.white,
    },
    toggleLabel: { fontSize: 14, fontWeight: '600', color: colors.textPrimary },
    currentPlanCard: {
      backgroundColor: colors.surfaceElevated,
      borderRadius: 16,
      padding: 20,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 25,
    },
    currentPlanDesc: {
      color: colors.textSecondary,
      fontSize: 14,
      marginVertical: 12,
    },
    sectionTitle: {
      fontSize: 18,
      marginBottom: 20,
      color: colors.textPrimary,
    },
    planCard: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 16,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: colors.border,
      marginBottom: 12,
      backgroundColor: colors.surface,
    },
    selectedPlanCard: { borderColor: colors.primary },
    planName: { fontSize: 16, color: colors.textPrimary },
    planDesc: { fontSize: 12, color: colors.textSecondary },
    priceContainer: { alignItems: 'flex-end' },
    priceAmount: { fontSize: 20, color: colors.textPrimary },
    perMonthText: { color: colors.textSecondary },
    detailCard: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 24,
      overflow: 'hidden',
      elevation: 2,
      shadowColor: colors.black,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 10,
    },
    detailHeader: { padding: 20, paddingBottom: 10 },
    priceSection: {
      paddingHorizontal: 20,
      paddingBottom: 20,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.border,
    },
    priceAmountLarge: { fontSize: 32, color: colors.textPrimary },
    perMonth: {
      fontSize: 16,
      color: colors.textSecondary,
      marginLeft: 4,
      marginBottom: 4,
      alignSelf: 'flex-end',
    },
    creditsText: {
      fontSize: 14,
      color: colors.primary,
      marginTop: 4,
      fontWeight: '500',
    },
    featureBox: {
      padding: 20,
      backgroundColor: colors.surfaceElevated,
    },
    featureTitleBg: { marginBottom: 16 },
    featureTitle: { color: colors.textPrimary },
    featureRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      marginBottom: 12,
      gap: 12,
    },
    featureText: {
      fontSize: 14,
      color: colors.textSecondary,
      flex: 1,
      lineHeight: 20,
    },
    badge: {
      backgroundColor: colors.surfaceElevated,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 20,
      marginLeft: 10,
      borderWidth: 1,
      borderColor: colors.primary,
    },
    badgeText: { color: colors.primary },
    outlineBtn: {
      borderWidth: 1.5,
      borderColor: colors.border,
      borderRadius: 12,
      height: 56,
      justifyContent: 'center',
      alignItems: 'center',
    },
    outlineBtnText: { color: colors.textSecondary, fontSize: 16 },
  });
}

/** Profile/info screens: dm-details, user-detail, group-user-detail, channel-user-detail. */
export function createChatInfoStyles(colors: ThemeColors) {
  return StyleSheet.create({
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingVertical: 12,
      alignItems: 'center',
      backgroundColor: colors.surface,
    },
    iconBtn: { padding: 4 },
    profileHero: {
      alignItems: 'center',
      paddingTop: 24,
      paddingBottom: 32,
      backgroundColor: colors.surface,
    },
    mainAvatarContainer: {
      position: 'relative',
      marginBottom: 20,
    },
    mainAvatar: {
      width: 200,
      height: 200,
      borderRadius: 100,
      backgroundColor: colors.reactionBackground,
    },
    onlineStatus: {
      position: 'absolute',
      bottom: 12,
      right: 12,
      width: 26,
      height: 26,
      borderRadius: 13,
      borderWidth: 4,
      borderColor: colors.white,
    },
    userName: { fontSize: 26, color: colors.textPrimary },
    userTitle: {
      fontSize: 15,
      color: colors.messageMeta,
      marginTop: 4,
      letterSpacing: 0.5,
    },
    statusBubble: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surfaceElevated,
      paddingHorizontal: 18,
      paddingVertical: 10,
      borderRadius: 24,
      marginTop: 18,
      maxWidth: '85%',
      borderWidth: 1,
      borderColor: colors.border,
    },
    statusEmoji: { fontSize: 18, marginRight: 8 },
    statusText: { fontSize: 14, color: colors.iconDefault },
    quickActionRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      gap: 32,
      marginTop: 30,
      width: '100%',
    },
    circleAction: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    actionIconCircle: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: colors.lightBlue,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 8,
    },
    circleActionText: {
      color: colors.primary,
      fontWeight: '600',
    },
    contentSection: {
      padding: 20,
      backgroundColor: colors.surface,
    },
    sectionTitle: {
      fontSize: 16,
      color: colors.textPrimary,
    },
    detailsGrid: { gap: 16 },
    infoCard: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surfaceElevated,
      padding: 14,
      borderRadius: 14,
    },
    divider: { height: 8, backgroundColor: colors.reactionBackground },
    sectionPadding: { padding: 20, backgroundColor: colors.surface },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 15,
      alignItems: 'center',
    },
    mediaCount: { flexDirection: 'row', alignItems: 'center' },
    mediaScroll: { flexDirection: 'row', alignItems: 'center', columnGap: 10 },
    mediaWrapper: {
      position: 'relative',
      marginRight: 12,
    },
    mediaThumb: {
      width: 110,
      height: 110,
      borderRadius: 14,
      backgroundColor: colors.reactionBackground,
      borderWidth: 1,
      borderColor: colors.border,
    },
    playOverlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0,0,0,0.2)',
      borderRadius: 14,
    },
    settingsSection: { backgroundColor: colors.surface },
    actionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 16,
      paddingHorizontal: 20,
    },
    actionBorder: {
      borderBottomWidth: 0.5,
      borderBottomColor: colors.reactionBackground,
    },
    actionLeading: { flexDirection: 'row', alignItems: 'center' },
    actionIconBg: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: colors.surfaceElevated,
      justifyContent: 'center',
      alignItems: 'center',
    },
    actionTextContainer: { marginLeft: 16 },
    actionLabel: { fontSize: 16, color: colors.textPrimary },
    videoWrapper: {
      position: 'relative',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 10,
    },
    playIconOverlay: {
      position: 'absolute',
      borderRadius: 20,
      padding: 4,
    },
  });
}

/** Group/channel info screens: group-details, channel-details. */
export function createGroupInfoStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.reactionBackground },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 15,
      paddingVertical: 10,
      alignItems: 'center',
    },
    groupInfoContainer: {
      alignItems: 'center',
      paddingHorizontal: 30,
      paddingBottom: 20,
    },
    avatarStack: { flexDirection: 'row', alignItems: 'center', marginLeft: 5 },
    stackItem: {
      width: 65,
      height: 65,
      borderRadius: 50,
      borderWidth: 2,
      borderColor: colors.border,
    },
    stackOver: { marginLeft: -15 },
    avatarBadge: {
      position: 'absolute',
      bottom: -2,
      right: -5,
      backgroundColor: colors.textMuted,
      width: 22,
      height: 22,
      borderRadius: 11,
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 10,
      borderWidth: 2,
      borderColor: colors.reactionBackground,
    },
    groupName: {
      fontSize: 18,
      lineHeight: 24,
      marginTop: 5,
      textAlign: 'center',
      color: colors.textPrimary,
    },
    quickActions: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 20,
      width: '100%',
      marginTop: 25,
    },
    quickActionBtn: {
      alignItems: 'center',
      flex: 1,
      borderRadius: 12,
      borderWidth: 0.5,
      borderColor: colors.primary,
      padding: 12,
      justifyContent: 'center',
    },
    iconCircle: { marginBottom: 3 },
    divider: {
      height: 8,
      backgroundColor: colors.border,
      width: '100%',
    },
    sectionPadding: { padding: 16 },
    sectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 15,
      alignItems: 'center',
    },
    mediaCount: { flexDirection: 'row', alignItems: 'center' },
    mediaScroll: { flexDirection: 'row' },
    mediaThumb: {
      width: 90,
      height: 90,
      borderRadius: 10,
      marginRight: 10,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.border,
    },
    actionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 16,
    },
    actionLeading: { flexDirection: 'row', alignItems: 'center' },
    actionTextContainer: { marginLeft: 15 },
    actionLabel: { fontSize: 16, color: colors.textPrimary },
    memberRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
    },
    memberAvatar: {
      width: 48,
      height: 48,
      borderRadius: 24,
      borderWidth: 0.5,
      borderColor: colors.primary,
    },
    memberInfo: { flex: 1, marginLeft: 10 },
    addMemberIcon: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    linkIcon: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
    },
    adminBadge: {
      backgroundColor: colors.channelAvatarBackground,
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderRadius: 4,
      borderWidth: 1,
      borderColor: colors.border,
    },
    memberCheckboxBtn: {
      marginRight: 12,
      padding: 2,
    },
    removeMembersBar: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: colors.surface,
      borderTopWidth: 1,
      borderTopColor: colors.border,
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 24,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    removeMembersCount: {
      color: colors.messageMeta,
    },
    removeMembersBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.error,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 10,
      gap: 6,
    },
    removeMembersBtnText: {
      color: colors.white,
    },
    videoWrapper: {
      position: 'relative',
      justifyContent: 'center',
      alignItems: 'center',
    },
    playIconOverlay: {
      position: 'absolute',
      borderRadius: 20,
      padding: 4,
    },
  });
}

/** Member picker screens: add-member, group-add-members, channel add-members. */
export function createMemberPickerStyles(colors: ThemeColors) {
  return StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: colors.reactionBackground },
    navHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
      paddingVertical: 15,
      backgroundColor: colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: colors.reactionBackground,
    },
    navTitleCenter: { alignItems: 'center' },
    navTitle: { fontSize: 17, fontWeight: '700', color: colors.textPrimary },
    navCount: { fontSize: 12, color: colors.messageMeta },
    navActionText: { fontSize: 16, color: colors.primary },
    searchSection: {
      backgroundColor: colors.surface,
      paddingHorizontal: 20,
      paddingVertical: 12,
    },
    searchWrapper: {
      flexDirection: 'row',
      backgroundColor: colors.reactionBackground,
      borderRadius: 12,
      paddingHorizontal: 12,
      alignItems: 'center',
      height: 44,
    },
    input: {
      flex: 1,
      fontSize: 16,
      color: colors.textPrimary,
      paddingVertical: 0,
    },
    contentContainer: { flex: 1, flexDirection: 'row' },
    scrollContent: { paddingLeft: 20, paddingRight: 10, paddingBottom: 50 },
    listHeader: { marginBottom: 10 },
    selectedContainer: {
      backgroundColor: colors.surface,
      padding: 15,
      borderRadius: 16,
      marginTop: 15,
    },
    selectedItem: { alignItems: 'center', marginRight: 15, width: 60 },
    selectedAvatar: { width: 50, height: 50, borderRadius: 25 },
    removeBadge: {
      position: 'absolute',
      right: -2,
      top: -2,
      backgroundColor: colors.messageMeta,
      borderRadius: 10,
      padding: 2,
      borderWidth: 2,
      borderColor: colors.white,
    },
    selectedName: {
      fontSize: 12,
      marginTop: 5,
      color: colors.textPrimary,
      textAlign: 'center',
    },
    sectionHeader: {
      fontSize: 14,
      color: colors.messageMeta,
      marginTop: 20,
      marginBottom: 8,
    },
    groupCard: { backgroundColor: colors.surface },
    cardTop: { borderTopLeftRadius: 16, borderTopRightRadius: 16 },
    cardBottom: { borderBottomLeftRadius: 16, borderBottomRightRadius: 16 },
    userRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 14,
      paddingHorizontal: 0,
    },
    rowBorder: {
      borderBottomWidth: 1,
      borderBottomColor: colors.reactionBackground,
    },
    userInfo: { flexDirection: 'row', alignItems: 'center' },
    avatar: { width: 40, height: 40, borderRadius: 20, marginRight: 12 },
    avatarPlaceholder: {
      backgroundColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
    },
    userName: { fontSize: 15, fontWeight: '600', color: colors.textPrimary },
    userRole: { fontSize: 13, color: colors.messageMeta },
    radioCircle: {
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: colors.border,
      justifyContent: 'center',
      alignItems: 'center',
    },
    radioActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    alphabetSidebar: {
      width: 30,
      justifyContent: 'center',
      alignItems: 'center',
      paddingRight: 5,
    },
    alphabetText: {
      fontSize: 10,
      color: colors.primary,
      fontWeight: '600',
      paddingVertical: 1.5,
    },
    footerLoader: {
      paddingVertical: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    emptyStateContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 32,
    },
    emptyStateText: {
      color: colors.messageMeta,
      fontSize: 16,
      textAlign: 'center',
    },
    searchLabel: { color: colors.messageMeta, marginRight: 8 },
    navActionBold: { color: colors.primary, fontWeight: '700' },
    navActionRow: { flexDirection: 'row', alignItems: 'center' },
  });
}
