import { Dimensions, Platform, StyleSheet } from 'react-native';
import { normalize } from '@/utils/normalize';
import type { ThemeColors } from './types';

const { width: screenWidth } = Dimensions.get('window');

export function createChannelSetupStyles(colors: ThemeColors) {
  return {
    browseChannels: StyleSheet.create({
      container: { flex: 1, backgroundColor: colors.white },
      topHeader: {
        paddingHorizontal: normalize(20),
        paddingVertical: normalize(20),
        backgroundColor: colors.secondary,
      },
      profileTop: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
      },
      searchBar: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.secondaryforeground,
        height: normalize(40),
        borderRadius: normalize(8),
        paddingHorizontal: normalize(12),
      },
      searchIcon: {
        width: 18,
        height: 18,
        tintColor: colors.white,
        marginRight: 8,
      },
      searchInput: {
        flex: 1,
        fontSize: normalize(15),
        color: colors.white,
      },
      avatarContainer: {
        marginLeft: 15,
        position: 'relative',
      },
      profilePic: {
        width: normalize(40),
        height: normalize(40),
        borderRadius: normalize(20),
        borderWidth: 1,
        borderColor: colors.white,
      },
      onlineBadge: {
        position: 'absolute',
        bottom: 2,
        right: 0,
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: colors.online,
        borderWidth: 1,
        borderColor: colors.white,
      },
      listContent: {
        paddingHorizontal: normalize(20),
        paddingTop: normalize(20),
        paddingBottom: normalize(100),
      },
      chatItem: {
        flexDirection: 'row',
        marginBottom: normalize(25),
        alignItems: 'center',
      },
      avatarWrapper: {
        position: 'relative',
        backgroundColor: colors.channelAvatarBackground,
        width: normalize(45),
        height: normalize(45),
        borderRadius: normalize(28),
        alignItems: 'center',
        justifyContent: 'center',
      },
      itemOnlineBadge: {
        position: 'absolute',
        bottom: 2,
        right: 2,
        width: 12,
        height: 12,
        borderRadius: 6,
        backgroundColor: colors.online,
        borderWidth: 2,
        borderColor: colors.white,
      },
      chatInfo: { flex: 1, marginLeft: 15 },
      chatHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 4,
      },
      chatName: {
        flex: 1,
        color: colors.textPrimary,
        marginRight: 10,
      },
      chatTime: { color: colors.textSecondary },
      chatFooterRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
      },
      chatMsg: { color: colors.textMuted, flex: 1, marginRight: 10 },
      countBadge: {
        backgroundColor: colors.primary,
        minWidth: 20,
        height: 20,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 4,
      },
      countText: { color: colors.white },
      fab: {
        position: 'absolute',
        right: normalize(20),
        bottom: normalize(180),
        width: normalize(56),
        height: normalize(56),
        borderRadius: normalize(28),
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 5,
        shadowColor: colors.black,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
      },
      plusIcon: { width: 24, height: 24, tintColor: colors.white },
    }),
    createChannel: StyleSheet.create({
      container: { flex: 1, backgroundColor: colors.bgSecondary },
      header: {
        height: 56,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        backgroundColor: colors.surface,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: colors.border,
      },
      headerBtn: { flexDirection: 'row', alignItems: 'center', minWidth: 60 },
      scrollContent: { padding: 16 },
      inputCard: {
        backgroundColor: colors.surface,
        borderRadius: 12,
        overflow: 'hidden',
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: colors.border,
        marginBottom: 20,
      },
      nameInputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingRight: 12,
        backgroundColor: colors.surfaceElevated,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: colors.transparent,
      },
      avatarPicker: {
        padding: 12,
      },
      hashCircle: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: colors.channelAvatarBackground,
        justifyContent: 'center',
        alignItems: 'center',
      },
      selectionRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        height: 52,
      },
      divider: {
        height: StyleSheet.hairlineWidth,
        backgroundColor: colors.border,
        marginLeft: 16,
      },
      sectionLabel: {
        marginTop: 24,
        marginBottom: 8,
        marginLeft: 4,
        color: colors.textSecondary,
      },
      helperText: {
        marginTop: 8,
        marginLeft: 4,
        color: colors.iconMuted,
        lineHeight: 18,
      },
      button: {
        backgroundColor: colors.primary,
        height: normalize(52),
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
        marginTop: 20,
        flexDirection: 'row',
        gap: 5,
      },
    }),
    channelOnboarding: StyleSheet.create({
      container: {
        backgroundColor: colors.surface,
        paddingHorizontal: normalize(24),
      },
      illustrationContainer: {
        alignItems: 'center',
        marginTop: normalize(20),
      },
      imageCard: {
        width: screenWidth * 0.55,
        height: screenWidth * 0.55,
        backgroundColor: colors.surfaceElevated,
        borderRadius: 20,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.border,
      },
      illustration: {
        width: '80%',
        height: '80%',
      },
      pagination: {
        flexDirection: 'row',
        marginTop: normalize(25),
        alignItems: 'center',
      },
      dot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: colors.border,
        marginHorizontal: 4,
      },
      activeDot: {
        backgroundColor: colors.primary,
        width: 8,
        height: 8,
      },
      content: {
        marginTop: normalize(30),
        alignItems: 'center',
      },
      title: {
        fontSize: 26,
        color: colors.textPrimary,
        textAlign: 'center',
      },
      description: {
        fontSize: 16,
        color: colors.textSecondary,
        textAlign: 'center',
        marginTop: normalize(15),
        lineHeight: 24,
        paddingHorizontal: 10,
      },
      footer: {
        marginTop: 'auto',
        marginBottom: normalize(30),
      },
      button: {
        backgroundColor: colors.primary,
        height: normalize(52),
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
        width: '100%',
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
        marginTop: 20,
      },
    }),
    notificationPreference: StyleSheet.create({
      header: {
        height: normalize(56),
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
        borderBottomWidth: StyleSheet.hairlineWidth,
        borderBottomColor: colors.border,
      },
      backBtn: { flexDirection: 'row', alignItems: 'center', gap: 5 },
      headerTitle: { fontSize: 18, color: colors.black },
      headerIcon: {
        width: 20,
        height: 20,
        objectFit: 'contain',
        tintColor: colors.iconDefault,
      },
      scrollContent: {
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 40,
        flexGrow: 1,
      },
      formContainer: { marginTop: 10 },
      sectionLabel: {
        fontSize: 16,
        color: colors.textPrimary,
        marginBottom: 20,
        fontWeight: '600',
      },
      optionsGroup: {
        marginBottom: 20,
      },
      radioRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
      },
      radioLabel: {
        fontSize: 16,
        color: colors.textPrimary,
        marginLeft: 12,
      },
      checkboxGroup: {
        marginTop: 10,
        borderTopWidth: 1,
        borderTopColor: colors.threadBarBackground,
        paddingTop: 24,
      },
      checkboxRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
      },
      checkboxLabel: {
        fontSize: 16,
        color: colors.textPrimary,
        marginLeft: 12,
        flex: 1,
      },
      note: {
        color: colors.textSecondary,
        fontSize: 14,
        marginTop: 10,
        lineHeight: 20,
      },
      link: {
        color: colors.primary,
        textDecorationLine: 'underline',
      },
      bottomActions: {
        paddingHorizontal: 20,
        paddingBottom: Platform.OS === 'ios' ? 34 : 20,
        paddingTop: 12,
        borderTopWidth: StyleSheet.hairlineWidth,
        borderTopColor: colors.border,
        backgroundColor: colors.white,
      },
      buttonRow: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        gap: 12,
      },
      cancelButton: {
        height: normalize(48),
        paddingHorizontal: 20,
        justifyContent: 'center',
      },
      cancelText: {
        color: colors.textSecondary,
        fontSize: 16,
      },
      saveButton: {
        backgroundColor: colors.secondary,
        height: normalize(48),
        paddingHorizontal: 24,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        minWidth: 150,
        flexDirection: 'row',
      },
      saveText: {
        color: colors.white,
        fontSize: 16,
      },
    }),
    userAvatar: StyleSheet.create({
      avatarContainer: {
        position: 'relative',
      },
      onlineBadge: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        borderWidth: 2,
        borderColor: colors.white,
      },
    }),
  };
}

export function createAgentScreenStyles(colors: ThemeColors) {
  return {
    index: StyleSheet.create({
      topHeader: {
        paddingHorizontal: normalize(20),
        paddingVertical: normalize(20),
        backgroundColor: colors.secondary,
      },
      profileTop: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
      },
      searchBar: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.secondaryforeground,
        height: normalize(40),
        borderRadius: normalize(8),
        paddingHorizontal: normalize(12),
      },
      searchIcon: {
        width: 18,
        height: 18,
        tintColor: colors.white,
        marginRight: 8,
      },
      searchInput: {
        flex: 1,
        fontSize: normalize(15),
        color: colors.white,
      },
      avatarContainer: {
        marginLeft: 15,
        position: 'relative',
      },
      profilePic: {
        width: normalize(40),
        height: normalize(40),
        borderRadius: normalize(20),
        borderWidth: 1,
        borderColor: colors.white,
      },
      onlineBadge: {
        position: 'absolute',
        bottom: 2,
        right: 0,
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: colors.online,
        borderWidth: 1,
        borderColor: colors.white,
      },
      contentContainer: {
        flex: 1,
        backgroundColor: colors.white,
        borderTopLeftRadius: normalize(24),
        borderTopRightRadius: normalize(24),
        marginTop: normalize(5),
      },
      emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: normalize(40),
      },
      emptyImage: {
        width: screenWidth * 0.5,
        height: screenWidth * 0.4,
        marginBottom: normalize(20),
      },
      emptyTitle: {
        fontSize: normalize(18),
        color: colors.textMuted,
        marginBottom: normalize(10),
      },
      emptySubTitle: {
        fontSize: normalize(14),
        color: colors.iconMuted,
        textAlign: 'center',
        lineHeight: 20,
        marginBottom: normalize(30),
      },
      browseButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.primary,
        paddingVertical: normalize(12),
        paddingHorizontal: normalize(24),
        borderRadius: normalize(12),
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
      },
      browseButtonText: {
        color: colors.white,
        marginLeft: 8,
        fontSize: normalize(15),
      },
      listContent: { padding: normalize(20), paddingBottom: normalize(100) },
      agentItem: {
        flexDirection: 'row',
        marginBottom: normalize(25),
        alignItems: 'center',
      },
      avatarPlaceholder: {
        width: normalize(52),
        height: normalize(52),
        borderRadius: normalize(26),
        backgroundColor: colors.lightBlue,
        justifyContent: 'center',
        alignItems: 'center',
      },
      countBadge: {
        backgroundColor: colors.primary,
        minWidth: 20,
        height: 20,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 4,
      },
      countText: { color: colors.white },
      avatarImg: { width: normalize(40), height: normalize(40) },
      agentInfo: { flex: 1, marginLeft: normalize(15) },
      agentHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
      },
      agentName: { fontSize: normalize(15), color: colors.textPrimary },
      agentRole: {
        fontSize: normalize(12),
        color: colors.iconMuted,
        marginTop: 2,
        letterSpacing: 0.5,
      },
      agentDesc: {
        fontSize: normalize(14),
        color: colors.iconMuted,
        marginTop: 2,
        lineHeight: 20,
      },
      fab: {
        position: 'absolute',
        bottom: normalize(30),
        right: normalize(20),
        width: normalize(56),
        height: normalize(56),
        borderRadius: normalize(28),
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 8,
        shadowColor: colors.black,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
      },
      bottomTabPlaceholder: {
        height: normalize(60),
        backgroundColor: colors.white,
      },
    }),
    marketplace: StyleSheet.create({
      topHeader: {
        paddingHorizontal: normalize(20),
        paddingVertical: normalize(20),
        backgroundColor: colors.secondary,
      },
      profileTop: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
      },
      searchBar: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.secondaryforeground,
        height: normalize(40),
        borderRadius: normalize(8),
        paddingHorizontal: normalize(12),
      },
      searchIcon: {
        width: 18,
        height: 18,
        tintColor: colors.white,
        marginRight: 8,
      },
      searchInput: {
        flex: 1,
        fontSize: normalize(15),
        color: colors.white,
      },
      avatarContainer: {
        marginLeft: 15,
        position: 'relative',
      },
      profilePic: {
        width: normalize(40),
        height: normalize(40),
        borderRadius: normalize(20),
        borderWidth: 1,
        borderColor: colors.white,
      },
      onlineBadge: {
        position: 'absolute',
        bottom: 2,
        right: 0,
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: colors.online,
        borderWidth: 1,
        borderColor: colors.white,
      },
      contentContainer: {
        flex: 1,
        backgroundColor: colors.white,
        borderTopLeftRadius: normalize(24),
        borderTopRightRadius: normalize(24),
        marginTop: normalize(5),
      },
      emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: normalize(40),
      },
      emptyImage: {
        width: screenWidth * 0.5,
        height: screenWidth * 0.4,
        marginBottom: normalize(20),
      },
      emptyTitle: {
        fontSize: normalize(18),
        color: colors.textMuted,
        marginBottom: normalize(10),
      },
      emptySubTitle: {
        fontSize: normalize(14),
        color: colors.iconMuted,
        textAlign: 'center',
        lineHeight: 20,
        marginBottom: normalize(30),
      },
      browseButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.primary,
        paddingVertical: normalize(12),
        paddingHorizontal: normalize(24),
        borderRadius: normalize(12),
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 5,
      },
      browseButtonText: {
        color: colors.white,
        marginLeft: 8,
        fontSize: normalize(15),
      },
      listContent: { padding: normalize(16), paddingBottom: normalize(100) },
      agentItem: {
        flexDirection: 'row',
        marginBottom: normalize(25),
        alignItems: 'flex-start',
      },
      avatarPlaceholder: {
        width: normalize(52),
        height: normalize(52),
        borderRadius: normalize(26),
        backgroundColor: colors.lightBlue,
        justifyContent: 'center',
        alignItems: 'center',
      },
      countBadge: {
        backgroundColor: colors.primary,
        minWidth: 20,
        height: 20,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 4,
      },
      countText: { color: colors.white },
      avatarImg: { width: normalize(40), height: normalize(40) },
      agentInfo: { flex: 1, marginLeft: normalize(15) },
      agentHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
      },
      agentName: {
        fontSize: normalize(17),
        color: colors.textPrimary,
        width: '70%',
      },
      agentRole: {
        fontSize: normalize(12),
        color: colors.iconMuted,
        marginTop: 2,
        letterSpacing: 0.5,
      },
      agentDesc: {
        fontSize: normalize(14),
        color: colors.iconMuted,
        marginTop: 4,
        lineHeight: 20,
      },
      fab: {
        position: 'absolute',
        bottom: normalize(30),
        right: normalize(20),
        width: normalize(56),
        height: normalize(56),
        borderRadius: normalize(28),
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 8,
        shadowColor: colors.black,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
      },
      bottomTabPlaceholder: {
        height: normalize(60),
        backgroundColor: colors.white,
      },
    }),
    createAgent: StyleSheet.create({
      headerTitleContainer: {
        height: 120,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.secondary,
        position: 'relative',
      },
      backButton: {
        position: 'absolute',
        left: 20,
        top: 35,
        zIndex: 10,
      },
      whiteSheet: {
        flex: 1,
        backgroundColor: colors.white,
        borderTopLeftRadius: 25,
        borderTopRightRadius: 25,
        marginTop: -20,
      },
      scrollContent: {
        paddingHorizontal: 20,
        paddingBottom: 40,
      },
      avatarContainer: {
        alignItems: 'center',
        marginTop: 30,
        marginBottom: 20,
      },
      avatarCircle: {
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: colors.reactionBackground,
        justifyContent: 'center',
        alignItems: 'center',
      },
      avatarImg: {
        width: 80,
        height: 80,
        opacity: 0.2,
      },
      avatarImgSelected: {
        width: 120,
        height: 120,
        borderRadius: 60,
        opacity: 1,
      },
      plusBtn: {
        position: 'absolute',
        bottom: 5,
        right: 5,
        backgroundColor: colors.primary,
        width: 30,
        height: 30,
        borderRadius: 15,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: colors.white,
      },
      addAvatarText: {
        marginTop: 15,
        color: colors.textPrimary,
      },
      formSection: {
        marginTop: 10,
      },
      labelOverride: {
        marginBottom: normalize(8),
        color: colors.textMuted,
      },
      label: {
        marginBottom: 10,
        marginTop: 15,
        color: colors.textSecondary,
      },
      dropdown: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: normalize(8),
        paddingHorizontal: normalize(15),
        height: normalize(52),
        marginBottom: normalize(20),
        backgroundColor: colors.white,
      },
      textAreaWrapper: {
        position: 'relative',
      },
      textArea: {
        height: 100,
        textAlignVertical: 'top',
      },
      charCount: {
        position: 'absolute',
        bottom: -15,
        right: 0,
        color: colors.messageMeta,
      },
      visibilitySection: {
        marginTop: 20,
      },
      radioRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 12,
      },
      radioLabelContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        flex: 1,
      },
      subLabel: {
        color: colors.messageMeta,
        marginLeft: 8,
      },
      radioCircle: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: colors.messageMeta,
      },
      radioSelected: {
        borderColor: colors.primary,
        borderWidth: 6,
      },
      buttonRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 40,
        gap: 15,
      },
      cancelBtn: {
        flex: 1,
        height: 50,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: colors.border,
        justifyContent: 'center',
        alignItems: 'center',
      },
      createBtn: {
        flex: 1,
        height: 50,
        borderRadius: 10,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        gap: 5,
      },
      modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.2)',
        justifyContent: 'center',
        alignItems: 'center',
      },
      dropdownMenu: {
        width: '80%',
        backgroundColor: colors.white,
        borderRadius: 12,
        padding: 10,
        elevation: 5,
        shadowColor: colors.black,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
      },
      dropdownItem: {
        paddingVertical: 15,
        paddingHorizontal: 20,
        borderBottomWidth: 0.5,
        borderBottomColor: colors.border,
      },
    }),
    agentDetails: StyleSheet.create({
      container: {
        flex: 1,
        backgroundColor: colors.secondary,
      },
      header: {
        paddingHorizontal: normalize(16),
        paddingBottom: normalize(20),
      },
      headerContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: normalize(10),
      },
      backBtn: {
        padding: 4,
      },
      headerTitle: {
        fontSize: normalize(18),
        color: colors.white,
      },
      contentCard: {
        flex: 1,
        backgroundColor: colors.white,
        borderTopLeftRadius: normalize(24),
        borderTopRightRadius: normalize(24),
      },
      scrollContent: {
        paddingHorizontal: normalize(24),
        paddingTop: normalize(30),
        paddingBottom: normalize(40),
      },
      brandingSection: {
        alignItems: 'center',
        marginBottom: normalize(30),
      },
      avatarContainer: {
        width: normalize(100),
        height: normalize(100),
        borderRadius: normalize(50),
        backgroundColor: colors.lightBlue,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: normalize(16),
      },
      avatar: {
        width: normalize(60),
        height: normalize(60),
      },
      agentName: {
        fontSize: normalize(24),
        color: colors.textPrimary,
        marginBottom: normalize(8),
      },
      roleBadge: {
        backgroundColor: colors.chatSentBubble,
        paddingHorizontal: normalize(16),
        paddingVertical: normalize(6),
        borderRadius: normalize(8),
      },
      roleText: {
        fontSize: normalize(12),
        color: colors.secondary,
        letterSpacing: 0.5,
      },
      section: {
        marginTop: normalize(20),
      },
      sectionTitle: {
        fontSize: normalize(16),
        color: colors.textPrimary,
        marginBottom: normalize(12),
      },
      aboutText: {
        fontSize: normalize(14),
        color: colors.textSecondary,
        lineHeight: 22,
      },
      bulletRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginBottom: normalize(8),
        paddingLeft: normalize(4),
      },
      bullet: {
        width: 4,
        height: 4,
        borderRadius: 2,
        backgroundColor: colors.iconMuted,
        marginTop: 8,
        marginRight: normalize(10),
      },
      bulletText: {
        fontSize: normalize(14),
        color: colors.textSecondary,
        flex: 1,
        lineHeight: 20,
      },
      divider: {
        height: 1,
        backgroundColor: colors.threadBarBackground,
        marginTop: normalize(20),
      },
      removeButton: {
        marginTop: normalize(30),
        backgroundColor: 'rgba(255, 59, 48, 0.1)',
        height: normalize(56),
        borderRadius: normalize(12),
        justifyContent: 'center',
        alignItems: 'center',
      },
      removeButtonText: {
        color: colors.error,
        fontSize: normalize(16),
      },
    }),
    agentDetailsMarkdown: StyleSheet.create({
      body: {
        color: colors.textSecondary,
        fontSize: normalize(14),
        lineHeight: 22,
      },
      bullet_list: {
        marginTop: 10,
      },
      heading1: {
        color: colors.textPrimary,
        fontSize: normalize(18),
        marginBottom: 5,
      },
      strong: {
        fontWeight: 'bold',
        color: colors.textPrimary,
      },
      link: {
        color: colors.primary,
      },
    }),
    agentPopover: StyleSheet.create({
      wrapper: { ...StyleSheet.absoluteFillObject },
      overlay: { ...StyleSheet.absoluteFillObject },
      fab: {
        position: 'absolute',
        right: normalize(20),
        bottom: normalize(20),
        width: normalize(56),
        height: normalize(56),
        borderRadius: normalize(28),
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 5,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        zIndex: 100,
      },
      fabActive: { backgroundColor: colors.secondary },
      plusIcon: { width: 24, height: 24, tintColor: colors.white },
      popoverCard: {
        position: 'absolute',
        right: normalize(20),
        bottom: normalize(80),
        backgroundColor: colors.white,
        borderRadius: normalize(12),
        width: normalize(210),
        paddingVertical: normalize(4),
        zIndex: 101,
        ...Platform.select({
          ios: {
            shadowColor: colors.black,
            shadowOffset: { width: 0, height: 12 },
            shadowOpacity: 0.15,
            shadowRadius: 16,
          },
          android: { elevation: 12 },
        }),
      },
      menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: normalize(16),
      },
      menuIcon: {
        width: 22,
        height: 22,
        marginRight: 12,
        tintColor: colors.textPrimary,
      },
      menuText: { color: colors.textPrimary },
      separator: {
        height: 1,
        backgroundColor: colors.categoryChip,
        marginHorizontal: normalize(16),
      },
    }),
  };
}

export function createOrgScreenStyles(colors: ThemeColors) {
  return StyleSheet.create({
    scrollContainer: {
      paddingHorizontal: 24,
      paddingBottom: 40,
    },
    backBtn: {
      alignSelf: 'flex-start',
      marginTop: 10,
      marginBottom: 10,
      backgroundColor: colors.topNavigation,
      borderRadius: 20,
      padding: 8,
    },
    title: {
      textAlign: 'center',
      marginTop: 10,
      marginBottom: 8,
      color: colors.textPrimary,
    },
    subtitle: {
      textAlign: 'center',
      color: colors.textSecondary,
      marginBottom: 32,
    },
    formGroup: {
      marginBottom: 20,
    },
    label: {
      marginBottom: 8,
      color: colors.textPrimary,
    },
    countrySelectorText: {
      color: colors.textPrimary,
    },
    countrySelectorPlaceholder: {
      color: colors.textMuted,
    },
    input: {
      height: 52,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 16,
      fontSize: 16,
      backgroundColor: colors.bgSecondary,
      color: colors.textPrimary,
    },
    countrySelector: {
      height: 52,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 16,
      backgroundColor: colors.bgSecondary,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    submitBtn: {
      marginTop: 20,
      backgroundColor: colors.primary,
      borderRadius: 8,
      height: 52,
      flexDirection: 'row',
      gap: 3,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 2,
    },
  });
}

function createLegacyCallScreenBaseStyles(
  colors: ThemeColors,
  width: number,
  quickAccessBottom: number,
  containerBackground: string,
) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: containerBackground },
    safeArea: { flex: 1 },
    topHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
    },
    headerButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: `${colors.primaryforeground}59`,
      justifyContent: 'center',
      alignItems: 'center',
    },
    titleContainer: { alignItems: 'center' },
    contactName: { fontSize: 22, fontWeight: '700', color: colors.black },
    statusText: { fontSize: 14, color: colors.textSecondary },
    centerContent: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    avatarContainer: {
      width: width * 0.55,
      height: width * 0.55,
      borderRadius: (width * 0.55) / 2,
      overflow: 'hidden',
    },
    avatar: { width: '100%', height: '100%' },
    gridContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'center',
      padding: 10,
    },
    card: {
      width: (width - 60) / 2,
      height: 180,
      backgroundColor: colors.black,
      borderRadius: 20,
      margin: 8,
      alignItems: 'center',
      justifyContent: 'center',
    },
    cardAvatar: { width: 70, height: 70, borderRadius: 35 },
    cardName: { color: colors.white, marginTop: 12, fontWeight: '600' },
    invitedBadge: {
      position: 'absolute',
      top: 15,
      flexDirection: 'row',
      backgroundColor: 'rgba(0,0,0,0.3)',
      padding: 5,
      borderRadius: 10,
    },
    invitedText: { color: colors.white, fontSize: 10, marginLeft: 4 },
    bottomContainer: {
      position: 'relative',
      paddingHorizontal: 15,
      paddingBottom: 30,
    },
    controlBar: {
      flexDirection: 'row',
      backgroundColor: colors.black,
      borderRadius: 35,
      paddingVertical: 12,
      justifyContent: 'space-around',
      alignItems: 'center',
    },
    iconCircle: {
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: 'rgba(255, 255, 255, 0.15)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    whiteIcon: { backgroundColor: colors.white },
    endCallButton: {
      backgroundColor: colors.error,
      width: 56,
      height: 56,
      borderRadius: 28,
    },
    quickAccessRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 12,
      paddingVertical: 10,
      backgroundColor: colors.white,
      borderBottomWidth: 1,
      borderBottomColor: colors.reactionBackground,
      paddingHorizontal: 10,
      borderRadius: 25,
      height: 60,
      position: 'absolute',
      bottom: normalize(quickAccessBottom),
      right: 0,
      left: 0,
    },
    plusBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.categoryChip,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: colors.border,
    },
    inputIcon: { width: 24, height: 24, tintColor: colors.iconDefault },
  });
}

export function createLegacyCallScreenStyles(
  colors: ThemeColors,
  width = screenWidth,
) {
  return {
    callScreen: createLegacyCallScreenBaseStyles(
      colors,
      width,
      80,
      colors.topNavigation,
    ),
    groupCallScreen: createLegacyCallScreenBaseStyles(
      colors,
      width,
      80,
      colors.primary,
    ),
    channelCallScreen: createLegacyCallScreenBaseStyles(
      colors,
      width,
      90,
      colors.primary,
    ),
  };
}

export function createIncomingCallStyles(colors: ThemeColors) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: colors.secondary,
    },
    container: {
      flex: 1,
      backgroundColor: colors.secondary,
      paddingHorizontal: normalize(20),
      paddingTop: normalize(10),
      paddingBottom: normalize(24),
      overflow: 'hidden',
    },
    glowOrb: {
      position: 'absolute',
      borderRadius: 999,
      opacity: 0.16,
    },
    glowOrbTop: {
      width: normalize(220),
      height: normalize(220),
      top: normalize(-60),
      right: normalize(-70),
    },
    glowOrbBottom: {
      width: normalize(260),
      height: normalize(260),
      bottom: normalize(-120),
      left: normalize(-90),
    },
    glowOrbSide: {
      width: normalize(160),
      height: normalize(160),
      top: '36%',
      left: normalize(-65),
      opacity: 0.1,
    },
    topRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: normalize(12),
    },
    infoPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: normalize(6),
      paddingHorizontal: normalize(12),
      paddingVertical: normalize(8),
      borderRadius: normalize(999),
      backgroundColor: 'rgba(255,255,255,0.08)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
    },
    infoPillText: {
      color: colors.white,
      fontSize: normalize(12),
    },
    content: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    kicker: {
      fontSize: normalize(16),
      color: colors.white,
      letterSpacing: 0.4,
    },
    callerName: {
      marginTop: normalize(8),
      fontSize: normalize(30),
      color: colors.white,
      textAlign: 'center',
      textTransform: 'capitalize',
    },
    subText: {
      marginTop: normalize(8),
      fontSize: normalize(14),
      color: colors.white,
      textAlign: 'center',
    },
    avatarStage: {
      width: normalize(240),
      height: normalize(240),
      marginTop: normalize(34),
      justifyContent: 'center',
      alignItems: 'center',
    },
    pulseRing: {
      position: 'absolute',
      width: normalize(188),
      height: normalize(188),
      borderRadius: normalize(94),
      borderWidth: 1.5,
      borderColor: 'rgba(93, 232, 154, 0.55)',
      backgroundColor: 'rgba(93, 232, 154, 0.08)',
    },
    pulseRingSecondary: {
      borderColor: 'rgba(120, 250, 185, 0.35)',
    },
    avatarHalo: {
      width: normalize(156),
      height: normalize(156),
      borderRadius: normalize(78),
      padding: normalize(6),
      backgroundColor: 'rgba(255,255,255,0.1)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.14)',
    },
    avatar: {
      width: '100%',
      height: '100%',
      borderRadius: normalize(72),
    },
    statusCard: {
      width: '100%',
      marginTop: normalize(24),
      paddingHorizontal: normalize(18),
      paddingVertical: normalize(16),
      borderRadius: normalize(22),
      backgroundColor: 'rgba(255,255,255,0.08)',
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.08)',
    },
    statusRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: normalize(8),
    },
    liveDot: {
      width: normalize(10),
      height: normalize(10),
      borderRadius: normalize(5),
      backgroundColor: colors.online,
    },
    statusTitle: {
      color: colors.white,
      fontSize: normalize(15),
    },
    statusDescription: {
      marginTop: normalize(8),
      color: colors.white,
      fontSize: normalize(13),
      lineHeight: normalize(20),
    },
    bottomDock: {
      paddingTop: normalize(8),
    },
    loadingWrap: {
      height: normalize(104),
      justifyContent: 'center',
      alignItems: 'center',
      gap: normalize(10),
    },
    loadingText: {
      color: colors.white,
      fontSize: normalize(14),
    },
    actionRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: normalize(20),
    },
    actionGroup: {
      alignItems: 'center',
      gap: normalize(10),
    },
    actionButton: {
      width: normalize(74),
      height: normalize(74),
      borderRadius: normalize(37),
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: colors.black,
      shadowOpacity: 0.28,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 10 },
      elevation: 8,
    },
    declineButton: {
      backgroundColor: colors.error,
    },
    acceptButton: {
      backgroundColor: colors.online,
    },
    declineIcon: {
      transform: [{ rotate: '135deg' }],
    },
    actionLabel: {
      color: colors.white,
      fontSize: normalize(14),
    },
    footerHint: {
      marginTop: normalize(24),
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: normalize(8),
    },
    footerHintText: {
      color: colors.white,
      fontSize: normalize(12),
      textAlign: 'center',
    },
  });
}

export function createSharedUIStyles(colors: ThemeColors) {
  return {
    carousel: StyleSheet.create({
      container: { flex: 1 },
      paginationContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: normalize(8),
        paddingBottom: normalize(32),
        marginTop: normalize(16),
      },
      dot: {
        width: normalize(8),
        height: normalize(8),
        borderRadius: normalize(4),
      },
    }),
    popover: StyleSheet.create({
      backdrop: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: colors.transparent,
      },
      popoverContainer: {
        position: 'absolute',
        backgroundColor: colors.surface,
        borderRadius: normalize(12),
        shadowColor: colors.black,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 8,
        overflow: 'hidden',
      },
    }),
    modalSheet: StyleSheet.create({
      overlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'flex-end',
      },
      content: {
        backgroundColor: colors.white,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        width: '100%',
        overflow: 'hidden',
      },
      gestureArea: { width: '100%', paddingTop: 10 },
      handle: {
        width: 40,
        height: 5,
        backgroundColor: colors.iconMuted,
        alignSelf: 'center',
        borderRadius: 3,
      },
    }),
    userStatusLabel: StyleSheet.create({
      container: {
        flexDirection: 'row',
        alignItems: 'center',
        flexShrink: 1,
        maxWidth: 140,
      },
      emoji: {
        marginRight: 4,
      },
      text: {
        flexShrink: 1,
      },
    }),
    horizontalLoader: StyleSheet.create({
      container: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 3,
        backgroundColor: colors.topNavigation,
        zIndex: 1000,
        overflow: 'hidden',
      },
      fill: {
        height: '100%',
        width: screenWidth * 0.6,
        backgroundColor: colors.primary,
      },
    }),
  };
}

export function createImageCropperStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.black,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingTop: 36,
      paddingBottom: 12,
      backgroundColor: 'rgba(0, 0, 0, 0.8)',
    },
    headerTitle: {
      fontSize: 18,
      color: colors.white,
    },
    headerButtonText: {
      fontSize: 16,
      color: colors.white,
      paddingHorizontal: 8,
    },
    previewContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      position: 'relative',
      overflow: 'hidden',
    },
    imageContainer: {
      position: 'absolute',
    },
    overlayContainer: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: 'space-between',
      pointerEvents: 'none',
    },
    overlay: {
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    middleRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    cropFrame: {
      borderWidth: 2,
      borderColor: colors.primary,
      backgroundColor: colors.transparent,
      position: 'relative',
    },
    cornerTL: {
      position: 'absolute',
      width: 24,
      height: 24,
      borderTopWidth: 3,
      borderLeftWidth: 3,
      borderTopColor: colors.white,
      borderLeftColor: colors.white,
      top: -3,
      left: -3,
    },
    cornerTR: {
      position: 'absolute',
      width: 24,
      height: 24,
      borderTopWidth: 3,
      borderRightWidth: 3,
      borderTopColor: colors.white,
      borderRightColor: colors.white,
      top: -3,
      right: -3,
    },
    cornerBL: {
      position: 'absolute',
      width: 24,
      height: 24,
      borderBottomWidth: 3,
      borderLeftWidth: 3,
      borderBottomColor: colors.white,
      borderLeftColor: colors.white,
      bottom: -3,
      left: -3,
    },
    cornerBR: {
      position: 'absolute',
      width: 24,
      height: 24,
      borderBottomWidth: 3,
      borderRightWidth: 3,
      borderBottomColor: colors.white,
      borderRightColor: colors.white,
      bottom: -3,
      right: -3,
    },
    controls: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 20,
      paddingVertical: 16,
      backgroundColor: 'rgba(0, 0, 0, 0.8)',
      borderTopWidth: 1,
      borderTopColor: 'rgba(255, 255, 255, 0.1)',
    },
    controlButton: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: `${colors.primary}4D`,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: `${colors.primary}80`,
    },
    scaleIndicator: {
      position: 'absolute',
      top: 80,
      right: 16,
      backgroundColor: 'rgba(0, 0, 0, 0.7)',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.1)',
    },
    scaleText: {
      color: colors.white,
      fontSize: 14,
      fontWeight: '600',
    },
  });
}

export function createMediaPreviewModalStyles(
  colors: ThemeColors,
  width = screenWidth,
) {
  return StyleSheet.create({
    modalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.92)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalDismissArea: {
      ...StyleSheet.absoluteFillObject,
      zIndex: 0,
    },
    modalContent: {
      width: '100%',
      height: '100%',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1,
    },
    modalImage: {
      width,
      height: width,
      maxHeight: '80%',
      maxWidth: '98%',
      borderRadius: 12,
      backgroundColor: colors.surfaceElevated,
    },
    modalVideo: {
      width,
      height: width,
      maxHeight: '80%',
      maxWidth: '98%',
      borderRadius: 12,
      backgroundColor: colors.surfaceElevated,
    },
    modalCloseBtn: {
      position: 'absolute',
      top: 40,
      right: 24,
      zIndex: 10,
      backgroundColor: 'rgba(0,0,0,0.5)',
      borderRadius: 20,
      padding: 4,
    },
    filePreviewBox: {
      justifyContent: 'center',
      alignItems: 'center',
      padding: 32,
      backgroundColor: colors.white,
      borderRadius: 16,
    },
    fileName: {
      color: colors.textPrimary,
      fontSize: 16,
      marginTop: 12,
      textAlign: 'center',
      maxWidth: width * 0.8,
    },
  });
}

export function createMentionSkeletonStyles(colors: ThemeColors) {
  return StyleSheet.create({
    card: {
      backgroundColor: colors.white,
      paddingHorizontal: normalize(16),
      paddingVertical: normalize(10),
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    channelBar: {
      height: normalize(28),
      backgroundColor: colors.threadBarBackground,
      borderRadius: normalize(6),
      marginBottom: normalize(8),
    },
    row: { flexDirection: 'row', alignItems: 'flex-start' },
    avatar: {
      width: normalize(40),
      height: normalize(40),
      borderRadius: normalize(20),
      backgroundColor: colors.skeleton,
      marginRight: normalize(12),
    },
    content: { flex: 1 },
    headerRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: normalize(6),
    },
    name: {
      width: '40%',
      height: 14,
      borderRadius: 4,
      backgroundColor: colors.skeleton,
    },
    time: {
      width: 50,
      height: 12,
      borderRadius: 4,
      backgroundColor: colors.skeleton,
    },
    line: {
      width: '70%',
      height: 12,
      borderRadius: 4,
      backgroundColor: colors.skeleton,
      marginBottom: normalize(6),
    },
    badge: {
      width: 60,
      height: 18,
      borderRadius: 8,
      backgroundColor: colors.skeleton,
    },
  });
}
